package ome.model;

import ome.util.BaseModelUtils;
import ome.util.Filterable;
import ome.util.Filter;


import java.util.*;




/**
 * Category generated by hbm2java
 */
public class
Category 
implements java.io.Serializable ,
ome.api.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer attributeId;
     private String name;
     private String description;
     private Set classifications;
     private CategoryGroup categoryGroup;
     private ModuleExecution moduleExecution;


    // Constructors

    /** default constructor */
    public Category() {
    }
    
    /** constructor with id */
    public Category(Integer attributeId) {
        this.attributeId = attributeId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getAttributeId() {
        return this.attributeId;
    }
    
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public Set getClassifications() {
        return this.classifications;
    }
    
    public void setClassifications(Set classifications) {
        this.classifications = classifications;
    }

    /**
     * 
     */
    public CategoryGroup getCategoryGroup() {
        return this.categoryGroup;
    }
    
    public void setCategoryGroup(CategoryGroup categoryGroup) {
        this.categoryGroup = categoryGroup;
    }

    /**
     * 
     */
    public ModuleExecution getModuleExecution() {
        return this.moduleExecution;
    }
    
    public void setModuleExecution(ModuleExecution moduleExecution) {
        this.moduleExecution = moduleExecution;
    }






  public boolean acceptFilter(Filter filter){


	  // Visiting: AttributeId ------------------------------------------
	  Integer _AttributeId = null;
	  try {
	     _AttributeId = getAttributeId();
	  } catch (Exception e) {
		 setAttributeId(null);
	  }

	  setAttributeId((Integer) filter.filter(ATTRIBUTEID,_AttributeId)); 

	  // Visiting: Name ------------------------------------------
	  String _Name = null;
	  try {
	     _Name = getName();
	  } catch (Exception e) {
		 setName(null);
	  }

	  setName((String) filter.filter(NAME,_Name)); 

	  // Visiting: Description ------------------------------------------
	  String _Description = null;
	  try {
	     _Description = getDescription();
	  } catch (Exception e) {
		 setDescription(null);
	  }

	  setDescription((String) filter.filter(DESCRIPTION,_Description)); 

	  // Visiting: Classifications ------------------------------------------
	  Set _Classifications = null;
	  try {
	     _Classifications = getClassifications();
	  } catch (Exception e) {
		 setClassifications(null);
	  }

	  setClassifications((Set) filter.filter(CLASSIFICATIONS,_Classifications)); 

	  // Visiting: CategoryGroup ------------------------------------------
	  CategoryGroup _CategoryGroup = null;
	  try {
	     _CategoryGroup = getCategoryGroup();
	  } catch (Exception e) {
		 setCategoryGroup(null);
	  }

	  setCategoryGroup((CategoryGroup) filter.filter(CATEGORYGROUP,_CategoryGroup)); 

	  // Visiting: ModuleExecution ------------------------------------------
	  ModuleExecution _ModuleExecution = null;
	  try {
	     _ModuleExecution = getModuleExecution();
	  } catch (Exception e) {
		 setModuleExecution(null);
	  }

	  setModuleExecution((ModuleExecution) filter.filter(MODULEEXECUTION,_ModuleExecution)); 
   	 return true;
  }
  
  public String toString(){
	return "Category"+(attributeId==null ? ":Hash_"+this.hashCode() : ":Id_"+attributeId);
  }
  
  // FIELD-FIELDS
  
	public final static String ATTRIBUTEID = "Category_AttributeId";
	public final static String NAME = "Category_Name";
	public final static String DESCRIPTION = "Category_Description";
	public final static String CLASSIFICATIONS = "Category_Classifications";
	public final static String CATEGORYGROUP = "Category_CategoryGroup";
	public final static String MODULEEXECUTION = "Category_ModuleExecution";
 	public final static Set FIELDS = new HashSet();
	static {
	   FIELDS.add(ATTRIBUTEID);
	   FIELDS.add(NAME);
	   FIELDS.add(DESCRIPTION);
	   FIELDS.add(CLASSIFICATIONS);
	   FIELDS.add(CATEGORYGROUP);
	   FIELDS.add(MODULEEXECUTION);
 	}


}
