package ome.model;

import ome.util.BaseModelUtils;
import ome.util.Filterable;
import ome.util.Filter;


import java.util.*;




/**
 * FormalInput generated by hbm2java
 */
public class
FormalInput 
implements java.io.Serializable ,
ome.api.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer formalInputId;
     private Boolean userDefined;
     private String name;
     private Boolean optional;
     private String description;
     private Boolean list;
     private Module module;
     private SemanticType semanticType;
     private Set analysisChainLinks;


    // Constructors

    /** default constructor */
    public FormalInput() {
    }
    
    /** constructor with id */
    public FormalInput(Integer formalInputId) {
        this.formalInputId = formalInputId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getFormalInputId() {
        return this.formalInputId;
    }
    
    public void setFormalInputId(Integer formalInputId) {
        this.formalInputId = formalInputId;
    }

    /**
     * 
     */
    public Boolean getUserDefined() {
        return this.userDefined;
    }
    
    public void setUserDefined(Boolean userDefined) {
        this.userDefined = userDefined;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public Boolean getOptional() {
        return this.optional;
    }
    
    public void setOptional(Boolean optional) {
        this.optional = optional;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public Boolean getList() {
        return this.list;
    }
    
    public void setList(Boolean list) {
        this.list = list;
    }

    /**
     * 
     */
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

    /**
     * 
     */
    public SemanticType getSemanticType() {
        return this.semanticType;
    }
    
    public void setSemanticType(SemanticType semanticType) {
        this.semanticType = semanticType;
    }

    /**
     * 
     */
    public Set getAnalysisChainLinks() {
        return this.analysisChainLinks;
    }
    
    public void setAnalysisChainLinks(Set analysisChainLinks) {
        this.analysisChainLinks = analysisChainLinks;
    }





	/** utility methods. Container may re-assign this. */	
	protected static ome.util.BaseModelUtils _utils = 
		new ome.util.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}

  public boolean acceptFilter(Filter filter){


	  // Visiting: FormalInputId ------------------------------------------
	  Integer _FormalInputId = null;
	  try {
	     _FormalInputId = getFormalInputId();
	  } catch (Exception e) {
		 setFormalInputId(null);
	  }
// TODO catch class cast?
	  setFormalInputId((Integer) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):FormalInputId",_FormalInputId)); 

	  // Visiting: UserDefined ------------------------------------------
	  Boolean _UserDefined = null;
	  try {
	     _UserDefined = getUserDefined();
	  } catch (Exception e) {
		 setUserDefined(null);
	  }
// TODO catch class cast?
	  setUserDefined((Boolean) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):UserDefined",_UserDefined)); 

	  // Visiting: Name ------------------------------------------
	  String _Name = null;
	  try {
	     _Name = getName();
	  } catch (Exception e) {
		 setName(null);
	  }
// TODO catch class cast?
	  setName((String) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):Name",_Name)); 

	  // Visiting: Optional ------------------------------------------
	  Boolean _Optional = null;
	  try {
	     _Optional = getOptional();
	  } catch (Exception e) {
		 setOptional(null);
	  }
// TODO catch class cast?
	  setOptional((Boolean) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):Optional",_Optional)); 

	  // Visiting: Description ------------------------------------------
	  String _Description = null;
	  try {
	     _Description = getDescription();
	  } catch (Exception e) {
		 setDescription(null);
	  }
// TODO catch class cast?
	  setDescription((String) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):Description",_Description)); 

	  // Visiting: List ------------------------------------------
	  Boolean _List = null;
	  try {
	     _List = getList();
	  } catch (Exception e) {
		 setList(null);
	  }
// TODO catch class cast?
	  setList((Boolean) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):List",_List)); 

	  // Visiting: Module ------------------------------------------
	  Module _Module = null;
	  try {
	     _Module = getModule();
	  } catch (Exception e) {
		 setModule(null);
	  }
// TODO catch class cast?
	  setModule((Module) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):Module",_Module)); 

	  // Visiting: SemanticType ------------------------------------------
	  SemanticType _SemanticType = null;
	  try {
	     _SemanticType = getSemanticType();
	  } catch (Exception e) {
		 setSemanticType(null);
	  }
// TODO catch class cast?
	  setSemanticType((SemanticType) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):SemanticType",_SemanticType)); 

	  // Visiting: AnalysisChainLinks ------------------------------------------
	  Set _AnalysisChainLinks = null;
	  try {
	     _AnalysisChainLinks = getAnalysisChainLinks();
	  } catch (Exception e) {
		 setAnalysisChainLinks(null);
	  }
// TODO catch class cast?
	  setAnalysisChainLinks((Set) filter.filter("org.hibernate.mapping.RootClass(ome.model.FormalInput):AnalysisChainLinks",_AnalysisChainLinks)); 
   	 return true;
  }
  
  public String toString(){
	return "FormalInput"+(formalInputId==null ? ":Hash"+this.hashCode() : ":"+formalInputId);
  }
  


}
