package ome.model;

import java.util.*;




/**
 * ImagePixel generated by hbm2java
 */
public class
ImagePixel 
implements java.io.Serializable ,
ome.api.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer attributeId;
     private String pixelType;
     private Integer sizeY;
     private Integer sizeZ;
     private String fileSha1;
     private Integer sizeT;
     private Long imageServerId;
     private Integer sizeX;
     private Integer sizeC;
     private Repository repository;
     private Set images;
     private Set channelComponents;
     private Image image;
     private ModuleExecution moduleExecution;


    // Constructors

    /** default constructor */
    public ImagePixel() {
    }
    
    /** constructor with id */
    public ImagePixel(Integer attributeId) {
        this.attributeId = attributeId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getAttributeId() {
        return this.attributeId;
    }
    
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * 
     */
    public String getPixelType() {
        return this.pixelType;
    }
    
    public void setPixelType(String pixelType) {
        this.pixelType = pixelType;
    }

    /**
     * 
     */
    public Integer getSizeY() {
        return this.sizeY;
    }
    
    public void setSizeY(Integer sizeY) {
        this.sizeY = sizeY;
    }

    /**
     * 
     */
    public Integer getSizeZ() {
        return this.sizeZ;
    }
    
    public void setSizeZ(Integer sizeZ) {
        this.sizeZ = sizeZ;
    }

    /**
     * 
     */
    public String getFileSha1() {
        return this.fileSha1;
    }
    
    public void setFileSha1(String fileSha1) {
        this.fileSha1 = fileSha1;
    }

    /**
     * 
     */
    public Integer getSizeT() {
        return this.sizeT;
    }
    
    public void setSizeT(Integer sizeT) {
        this.sizeT = sizeT;
    }

    /**
     * 
     */
    public Long getImageServerId() {
        return this.imageServerId;
    }
    
    public void setImageServerId(Long imageServerId) {
        this.imageServerId = imageServerId;
    }

    /**
     * 
     */
    public Integer getSizeX() {
        return this.sizeX;
    }
    
    public void setSizeX(Integer sizeX) {
        this.sizeX = sizeX;
    }

    /**
     * 
     */
    public Integer getSizeC() {
        return this.sizeC;
    }
    
    public void setSizeC(Integer sizeC) {
        this.sizeC = sizeC;
    }

    /**
     * 
     */
    public Repository getRepository() {
        return this.repository;
    }
    
    public void setRepository(Repository repository) {
        this.repository = repository;
    }

    /**
     * 
     */
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }

    /**
     * 
     */
    public Set getChannelComponents() {
        return this.channelComponents;
    }
    
    public void setChannelComponents(Set channelComponents) {
        this.channelComponents = channelComponents;
    }

    /**
     * 
     */
    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }

    /**
     * 
     */
    public ModuleExecution getModuleExecution() {
        return this.moduleExecution;
    }
    
    public void setModuleExecution(ModuleExecution moduleExecution) {
        this.moduleExecution = moduleExecution;
    }






  public boolean acceptFilter(ome.util.Filter filter){


	  // Visiting: AttributeId ------------------------------------------
	  Integer _AttributeId = null;
	  try {
	     _AttributeId = getAttributeId();
	  } catch (Exception e) {
		 setAttributeId(null);
	  }

	  setAttributeId((Integer) filter.filter(ATTRIBUTEID,_AttributeId)); 

	  // Visiting: PixelType ------------------------------------------
	  String _PixelType = null;
	  try {
	     _PixelType = getPixelType();
	  } catch (Exception e) {
		 setPixelType(null);
	  }

	  setPixelType((String) filter.filter(PIXELTYPE,_PixelType)); 

	  // Visiting: SizeY ------------------------------------------
	  Integer _SizeY = null;
	  try {
	     _SizeY = getSizeY();
	  } catch (Exception e) {
		 setSizeY(null);
	  }

	  setSizeY((Integer) filter.filter(SIZEY,_SizeY)); 

	  // Visiting: SizeZ ------------------------------------------
	  Integer _SizeZ = null;
	  try {
	     _SizeZ = getSizeZ();
	  } catch (Exception e) {
		 setSizeZ(null);
	  }

	  setSizeZ((Integer) filter.filter(SIZEZ,_SizeZ)); 

	  // Visiting: FileSha1 ------------------------------------------
	  String _FileSha1 = null;
	  try {
	     _FileSha1 = getFileSha1();
	  } catch (Exception e) {
		 setFileSha1(null);
	  }

	  setFileSha1((String) filter.filter(FILESHA1,_FileSha1)); 

	  // Visiting: SizeT ------------------------------------------
	  Integer _SizeT = null;
	  try {
	     _SizeT = getSizeT();
	  } catch (Exception e) {
		 setSizeT(null);
	  }

	  setSizeT((Integer) filter.filter(SIZET,_SizeT)); 

	  // Visiting: ImageServerId ------------------------------------------
	  Long _ImageServerId = null;
	  try {
	     _ImageServerId = getImageServerId();
	  } catch (Exception e) {
		 setImageServerId(null);
	  }

	  setImageServerId((Long) filter.filter(IMAGESERVERID,_ImageServerId)); 

	  // Visiting: SizeX ------------------------------------------
	  Integer _SizeX = null;
	  try {
	     _SizeX = getSizeX();
	  } catch (Exception e) {
		 setSizeX(null);
	  }

	  setSizeX((Integer) filter.filter(SIZEX,_SizeX)); 

	  // Visiting: SizeC ------------------------------------------
	  Integer _SizeC = null;
	  try {
	     _SizeC = getSizeC();
	  } catch (Exception e) {
		 setSizeC(null);
	  }

	  setSizeC((Integer) filter.filter(SIZEC,_SizeC)); 

	  // Visiting: Repository ------------------------------------------
	  Repository _Repository = null;
	  try {
	     _Repository = getRepository();
	  } catch (Exception e) {
		 setRepository(null);
	  }

	  setRepository((Repository) filter.filter(REPOSITORY,_Repository)); 

	  // Visiting: Images ------------------------------------------
	  Set _Images = null;
	  try {
	     _Images = getImages();
	  } catch (Exception e) {
		 setImages(null);
	  }

	  setImages((Set) filter.filter(IMAGES,_Images)); 

	  // Visiting: ChannelComponents ------------------------------------------
	  Set _ChannelComponents = null;
	  try {
	     _ChannelComponents = getChannelComponents();
	  } catch (Exception e) {
		 setChannelComponents(null);
	  }

	  setChannelComponents((Set) filter.filter(CHANNELCOMPONENTS,_ChannelComponents)); 

	  // Visiting: Image ------------------------------------------
	  Image _Image = null;
	  try {
	     _Image = getImage();
	  } catch (Exception e) {
		 setImage(null);
	  }

	  setImage((Image) filter.filter(IMAGE,_Image)); 

	  // Visiting: ModuleExecution ------------------------------------------
	  ModuleExecution _ModuleExecution = null;
	  try {
	     _ModuleExecution = getModuleExecution();
	  } catch (Exception e) {
		 setModuleExecution(null);
	  }

	  setModuleExecution((ModuleExecution) filter.filter(MODULEEXECUTION,_ModuleExecution)); 
   	 return true;
  }
  
  public String toString(){
	return "ImagePixel"+(attributeId==null ? ":Hash_"+this.hashCode() : ":Id_"+attributeId);
  }
  
  // FIELD-FIELDS
  
	public final static String ATTRIBUTEID = "ImagePixel_AttributeId";
	public final static String PIXELTYPE = "ImagePixel_PixelType";
	public final static String SIZEY = "ImagePixel_SizeY";
	public final static String SIZEZ = "ImagePixel_SizeZ";
	public final static String FILESHA1 = "ImagePixel_FileSha1";
	public final static String SIZET = "ImagePixel_SizeT";
	public final static String IMAGESERVERID = "ImagePixel_ImageServerId";
	public final static String SIZEX = "ImagePixel_SizeX";
	public final static String SIZEC = "ImagePixel_SizeC";
	public final static String REPOSITORY = "ImagePixel_Repository";
	public final static String IMAGES = "ImagePixel_Images";
	public final static String CHANNELCOMPONENTS = "ImagePixel_ChannelComponents";
	public final static String IMAGE = "ImagePixel_Image";
	public final static String MODULEEXECUTION = "ImagePixel_ModuleExecution";
 	public final static Set FIELDS = new HashSet();
	static {
	   FIELDS.add(ATTRIBUTEID);
	   FIELDS.add(PIXELTYPE);
	   FIELDS.add(SIZEY);
	   FIELDS.add(SIZEZ);
	   FIELDS.add(FILESHA1);
	   FIELDS.add(SIZET);
	   FIELDS.add(IMAGESERVERID);
	   FIELDS.add(SIZEX);
	   FIELDS.add(SIZEC);
	   FIELDS.add(REPOSITORY);
	   FIELDS.add(IMAGES);
	   FIELDS.add(CHANNELCOMPONENTS);
	   FIELDS.add(IMAGE);
	   FIELDS.add(MODULEEXECUTION);
 	}


}
