package ome.model;

import java.util.*;




/**
 * Module generated by hbm2java
 */
public class
Module 
implements java.io.Serializable ,
ome.api.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer moduleId;
     private String location;
     private String name;
     private String executionInstructions;
     private String description;
     private String moduleType;
     private String defaultIterator;
     private String newFeatureTag;
     private Set formalOutputs;
     private Set formalInputs;
     private Set moduleExecutions;
     private Set analysisChainNodes;


    // Constructors

    /** default constructor */
    public Module() {
    }
    
    /** constructor with id */
    public Module(Integer moduleId) {
        this.moduleId = moduleId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * 
     */
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getExecutionInstructions() {
        return this.executionInstructions;
    }
    
    public void setExecutionInstructions(String executionInstructions) {
        this.executionInstructions = executionInstructions;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public String getModuleType() {
        return this.moduleType;
    }
    
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * 
     */
    public String getDefaultIterator() {
        return this.defaultIterator;
    }
    
    public void setDefaultIterator(String defaultIterator) {
        this.defaultIterator = defaultIterator;
    }

    /**
     * 
     */
    public String getNewFeatureTag() {
        return this.newFeatureTag;
    }
    
    public void setNewFeatureTag(String newFeatureTag) {
        this.newFeatureTag = newFeatureTag;
    }

    /**
     * 
     */
    public Set getFormalOutputs() {
        return this.formalOutputs;
    }
    
    public void setFormalOutputs(Set formalOutputs) {
        this.formalOutputs = formalOutputs;
    }

    /**
     * 
     */
    public Set getFormalInputs() {
        return this.formalInputs;
    }
    
    public void setFormalInputs(Set formalInputs) {
        this.formalInputs = formalInputs;
    }

    /**
     * 
     */
    public Set getModuleExecutions() {
        return this.moduleExecutions;
    }
    
    public void setModuleExecutions(Set moduleExecutions) {
        this.moduleExecutions = moduleExecutions;
    }

    /**
     * 
     */
    public Set getAnalysisChainNodes() {
        return this.analysisChainNodes;
    }
    
    public void setAnalysisChainNodes(Set analysisChainNodes) {
        this.analysisChainNodes = analysisChainNodes;
    }






  public boolean acceptFilter(ome.util.Filter filter){


	  // Visiting: ModuleId ------------------------------------------
	  Integer _ModuleId = null;
	  try {
	     _ModuleId = getModuleId();
	  } catch (Exception e) {
		 setModuleId(null);
	  }

	  setModuleId((Integer) filter.filter(MODULEID,_ModuleId)); 

	  // Visiting: Location ------------------------------------------
	  String _Location = null;
	  try {
	     _Location = getLocation();
	  } catch (Exception e) {
		 setLocation(null);
	  }

	  setLocation((String) filter.filter(LOCATION,_Location)); 

	  // Visiting: Name ------------------------------------------
	  String _Name = null;
	  try {
	     _Name = getName();
	  } catch (Exception e) {
		 setName(null);
	  }

	  setName((String) filter.filter(NAME,_Name)); 

	  // Visiting: ExecutionInstructions ------------------------------------------
	  String _ExecutionInstructions = null;
	  try {
	     _ExecutionInstructions = getExecutionInstructions();
	  } catch (Exception e) {
		 setExecutionInstructions(null);
	  }

	  setExecutionInstructions((String) filter.filter(EXECUTIONINSTRUCTIONS,_ExecutionInstructions)); 

	  // Visiting: Description ------------------------------------------
	  String _Description = null;
	  try {
	     _Description = getDescription();
	  } catch (Exception e) {
		 setDescription(null);
	  }

	  setDescription((String) filter.filter(DESCRIPTION,_Description)); 

	  // Visiting: ModuleType ------------------------------------------
	  String _ModuleType = null;
	  try {
	     _ModuleType = getModuleType();
	  } catch (Exception e) {
		 setModuleType(null);
	  }

	  setModuleType((String) filter.filter(MODULETYPE,_ModuleType)); 

	  // Visiting: DefaultIterator ------------------------------------------
	  String _DefaultIterator = null;
	  try {
	     _DefaultIterator = getDefaultIterator();
	  } catch (Exception e) {
		 setDefaultIterator(null);
	  }

	  setDefaultIterator((String) filter.filter(DEFAULTITERATOR,_DefaultIterator)); 

	  // Visiting: NewFeatureTag ------------------------------------------
	  String _NewFeatureTag = null;
	  try {
	     _NewFeatureTag = getNewFeatureTag();
	  } catch (Exception e) {
		 setNewFeatureTag(null);
	  }

	  setNewFeatureTag((String) filter.filter(NEWFEATURETAG,_NewFeatureTag)); 

	  // Visiting: FormalOutputs ------------------------------------------
	  Set _FormalOutputs = null;
	  try {
	     _FormalOutputs = getFormalOutputs();
	  } catch (Exception e) {
		 setFormalOutputs(null);
	  }

	  setFormalOutputs((Set) filter.filter(FORMALOUTPUTS,_FormalOutputs)); 

	  // Visiting: FormalInputs ------------------------------------------
	  Set _FormalInputs = null;
	  try {
	     _FormalInputs = getFormalInputs();
	  } catch (Exception e) {
		 setFormalInputs(null);
	  }

	  setFormalInputs((Set) filter.filter(FORMALINPUTS,_FormalInputs)); 

	  // Visiting: ModuleExecutions ------------------------------------------
	  Set _ModuleExecutions = null;
	  try {
	     _ModuleExecutions = getModuleExecutions();
	  } catch (Exception e) {
		 setModuleExecutions(null);
	  }

	  setModuleExecutions((Set) filter.filter(MODULEEXECUTIONS,_ModuleExecutions)); 

	  // Visiting: AnalysisChainNodes ------------------------------------------
	  Set _AnalysisChainNodes = null;
	  try {
	     _AnalysisChainNodes = getAnalysisChainNodes();
	  } catch (Exception e) {
		 setAnalysisChainNodes(null);
	  }

	  setAnalysisChainNodes((Set) filter.filter(ANALYSISCHAINNODES,_AnalysisChainNodes)); 
   	 return true;
  }
  
  public String toString(){
	return "Module"+(moduleId==null ? ":Hash_"+this.hashCode() : ":Id_"+moduleId);
  }
  
  // FIELD-FIELDS
  
	public final static String MODULEID = "Module_ModuleId";
	public final static String LOCATION = "Module_Location";
	public final static String NAME = "Module_Name";
	public final static String EXECUTIONINSTRUCTIONS = "Module_ExecutionInstructions";
	public final static String DESCRIPTION = "Module_Description";
	public final static String MODULETYPE = "Module_ModuleType";
	public final static String DEFAULTITERATOR = "Module_DefaultIterator";
	public final static String NEWFEATURETAG = "Module_NewFeatureTag";
	public final static String FORMALOUTPUTS = "Module_FormalOutputs";
	public final static String FORMALINPUTS = "Module_FormalInputs";
	public final static String MODULEEXECUTIONS = "Module_ModuleExecutions";
	public final static String ANALYSISCHAINNODES = "Module_AnalysisChainNodes";
 	public final static Set FIELDS = new HashSet();
	static {
	   FIELDS.add(MODULEID);
	   FIELDS.add(LOCATION);
	   FIELDS.add(NAME);
	   FIELDS.add(EXECUTIONINSTRUCTIONS);
	   FIELDS.add(DESCRIPTION);
	   FIELDS.add(MODULETYPE);
	   FIELDS.add(DEFAULTITERATOR);
	   FIELDS.add(NEWFEATURETAG);
	   FIELDS.add(FORMALOUTPUTS);
	   FIELDS.add(FORMALINPUTS);
	   FIELDS.add(MODULEEXECUTIONS);
	   FIELDS.add(ANALYSISCHAINNODES);
 	}


}
