package ome.model;

import java.util.*;




/**
 * Project generated by hbm2java
 */
public class
Project 
implements java.io.Serializable ,
ome.api.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer projectId;
     private String view;
     private String name;
     private String description;
     private Set omeSessions;
     private Experimenter experimenter;
     private Group group;
     private Set datasets;


    // Constructors

    /** default constructor */
    public Project() {
    }
    
    /** constructor with id */
    public Project(Integer projectId) {
        this.projectId = projectId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * 
     */
    public String getView() {
        return this.view;
    }
    
    public void setView(String view) {
        this.view = view;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public Set getOmeSessions() {
        return this.omeSessions;
    }
    
    public void setOmeSessions(Set omeSessions) {
        this.omeSessions = omeSessions;
    }

    /**
     * 
     */
    public Experimenter getExperimenter() {
        return this.experimenter;
    }
    
    public void setExperimenter(Experimenter experimenter) {
        this.experimenter = experimenter;
    }

    /**
     * 
     */
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }

    /**
     * 
     */
    public Set getDatasets() {
        return this.datasets;
    }
    
    public void setDatasets(Set datasets) {
        this.datasets = datasets;
    }






  public boolean acceptFilter(ome.util.Filter filter){


	  // Visiting: ProjectId ------------------------------------------
	  Integer _ProjectId = null;
	  try {
	     _ProjectId = getProjectId();
	  } catch (Exception e) {
		 setProjectId(null);
	  }

	  setProjectId((Integer) filter.filter(PROJECTID,_ProjectId)); 

	  // Visiting: View ------------------------------------------
	  String _View = null;
	  try {
	     _View = getView();
	  } catch (Exception e) {
		 setView(null);
	  }

	  setView((String) filter.filter(VIEW,_View)); 

	  // Visiting: Name ------------------------------------------
	  String _Name = null;
	  try {
	     _Name = getName();
	  } catch (Exception e) {
		 setName(null);
	  }

	  setName((String) filter.filter(NAME,_Name)); 

	  // Visiting: Description ------------------------------------------
	  String _Description = null;
	  try {
	     _Description = getDescription();
	  } catch (Exception e) {
		 setDescription(null);
	  }

	  setDescription((String) filter.filter(DESCRIPTION,_Description)); 

	  // Visiting: OmeSessions ------------------------------------------
	  Set _OmeSessions = null;
	  try {
	     _OmeSessions = getOmeSessions();
	  } catch (Exception e) {
		 setOmeSessions(null);
	  }

	  setOmeSessions((Set) filter.filter(OMESESSIONS,_OmeSessions)); 

	  // Visiting: Experimenter ------------------------------------------
	  Experimenter _Experimenter = null;
	  try {
	     _Experimenter = getExperimenter();
	  } catch (Exception e) {
		 setExperimenter(null);
	  }

	  setExperimenter((Experimenter) filter.filter(EXPERIMENTER,_Experimenter)); 

	  // Visiting: Group ------------------------------------------
	  Group _Group = null;
	  try {
	     _Group = getGroup();
	  } catch (Exception e) {
		 setGroup(null);
	  }

	  setGroup((Group) filter.filter(GROUP,_Group)); 

	  // Visiting: Datasets ------------------------------------------
	  Set _Datasets = null;
	  try {
	     _Datasets = getDatasets();
	  } catch (Exception e) {
		 setDatasets(null);
	  }

	  setDatasets((Set) filter.filter(DATASETS,_Datasets)); 
   	 return true;
  }
  
  public String toString(){
	return "Project"+(projectId==null ? ":Hash_"+this.hashCode() : ":Id_"+projectId);
  }
  
  // FIELD-FIELDS
  
	public final static String PROJECTID = "Project_ProjectId";
	public final static String VIEW = "Project_View";
	public final static String NAME = "Project_Name";
	public final static String DESCRIPTION = "Project_Description";
	public final static String OMESESSIONS = "Project_OmeSessions";
	public final static String EXPERIMENTER = "Project_Experimenter";
	public final static String GROUP = "Project_Group";
	public final static String DATASETS = "Project_Datasets";
 	public final static Set FIELDS = new HashSet();
	static {
	   FIELDS.add(PROJECTID);
	   FIELDS.add(VIEW);
	   FIELDS.add(NAME);
	   FIELDS.add(DESCRIPTION);
	   FIELDS.add(OMESESSIONS);
	   FIELDS.add(EXPERIMENTER);
	   FIELDS.add(GROUP);
	   FIELDS.add(DATASETS);
 	}


}
