package ome.model;

import ome.util.BaseModelUtils;
import ome.util.Filterable;
import ome.util.Filter;


import java.util.*;




/**
 * SemanticTypeOutput generated by hbm2java
 */
public class
SemanticTypeOutput 
implements java.io.Serializable ,
ome.api.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer semanticTypeOutputId;
     private SemanticType semanticType;
     private ModuleExecution moduleExecution;


    // Constructors

    /** default constructor */
    public SemanticTypeOutput() {
    }
    
    /** constructor with id */
    public SemanticTypeOutput(Integer semanticTypeOutputId) {
        this.semanticTypeOutputId = semanticTypeOutputId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getSemanticTypeOutputId() {
        return this.semanticTypeOutputId;
    }
    
    public void setSemanticTypeOutputId(Integer semanticTypeOutputId) {
        this.semanticTypeOutputId = semanticTypeOutputId;
    }

    /**
     * 
     */
    public SemanticType getSemanticType() {
        return this.semanticType;
    }
    
    public void setSemanticType(SemanticType semanticType) {
        this.semanticType = semanticType;
    }

    /**
     * 
     */
    public ModuleExecution getModuleExecution() {
        return this.moduleExecution;
    }
    
    public void setModuleExecution(ModuleExecution moduleExecution) {
        this.moduleExecution = moduleExecution;
    }






  public boolean acceptFilter(Filter filter){


	  // Visiting: SemanticTypeOutputId ------------------------------------------
	  Integer _SemanticTypeOutputId = null;
	  try {
	     _SemanticTypeOutputId = getSemanticTypeOutputId();
	  } catch (Exception e) {
		 setSemanticTypeOutputId(null);
	  }
// TODO catch class cast?
	  setSemanticTypeOutputId((Integer) filter.filter(SEMANTICTYPEOUTPUTID,_SemanticTypeOutputId)); 

	  // Visiting: SemanticType ------------------------------------------
	  SemanticType _SemanticType = null;
	  try {
	     _SemanticType = getSemanticType();
	  } catch (Exception e) {
		 setSemanticType(null);
	  }
// TODO catch class cast?
	  setSemanticType((SemanticType) filter.filter(SEMANTICTYPE,_SemanticType)); 

	  // Visiting: ModuleExecution ------------------------------------------
	  ModuleExecution _ModuleExecution = null;
	  try {
	     _ModuleExecution = getModuleExecution();
	  } catch (Exception e) {
		 setModuleExecution(null);
	  }
// TODO catch class cast?
	  setModuleExecution((ModuleExecution) filter.filter(MODULEEXECUTION,_ModuleExecution)); 
   	 return true;
  }
  
  public String toString(){
	return "SemanticTypeOutput"+(semanticTypeOutputId==null ? ":Hash_"+this.hashCode() : ":Id_"+semanticTypeOutputId);
  }
  
  // FIELD-FIELDS
  
	public final static String SEMANTICTYPEOUTPUTID = "SemanticTypeOutput_SemanticTypeOutputId";
	public final static String SEMANTICTYPE = "SemanticTypeOutput_SemanticType";
	public final static String MODULEEXECUTION = "SemanticTypeOutput_ModuleExecution";
 	public final static Set FIELDS = new HashSet();
	static {
	   FIELDS.add(SEMANTICTYPEOUTPUTID);
	   FIELDS.add(SEMANTICTYPE);
	   FIELDS.add(MODULEEXECUTION);
 	}


}
