SUBDIR= src test

DISTCLEANFILES = \
	Makefile.in \
	config.cache \
	*.loT \
	aclocal.m4 \
	autoscan.log \
	compile \
	config.guess \
	config.h.in \
	config.sub \
	configure.scan \
	depcomp \
	install-sh \
	ltmain.sh \
	missing \
	mkinstalldirs\
	configure

all : slice src test

slice:
	@date
	cd src ; $(MAKE) $(MFLAGS) slice
	@date

src:
	@date
	cd src ; $(MAKE) $(MFLAGS)
	@date

test:
	@date
	cd test ; $(MAKE) $(MFLAGS) 
	@date

clean:
	@date
	cd src ; $(MAKE) $(MFLAGS) clean
	cd test ; $(MAKE) $(MFLAGS) clean
	@date

clean-all:
	cd src ; $(MAKE) $(MFLAGS) distclean && rm Makefile.in # Not sure why *.in is sticking around
	cd test ; $(MAKE) $(MFLAGS) distclean && rm Makefile.in 
	$(MAKE) $(MFLAGS) distclean

.PHONY: all src test clean clean-all
