#!/bin/sh
# This script is used for testing the build, primarily for use
# with travis, but may be used by hand as well.

set -e

if [ -z "$ICE_HOME" ]; then
  export ICE_HOME=/usr/share/Ice
fi

# Clean up
clean()
{
    ant clean
}

java_build()
{
    TEST="-p" ant build-default test-compile -Dpackage-extra=false
}

java_test()
{
    ant -f components/tools/OmeroJava/build.xml test -Dtest.with.fail=true
    ant -f components/model/build.xml test -Dtest.with.fail=true
    ant -f components/common/build.xml test -Dtest.with.fail=true
}

py_flake8()
{
    flake8 -v components/tools/OmeroPy/src
    flake8 -v components/tools/OmeroPy/test
    flake8 -v components/tools/OmeroWeb/omeroweb/webstart
    flake8 -v components/tools/OmeroWeb/omeroweb/webredirect
    flake8 -v components/tools/OmeroWeb/test
}

py_build()
{
    ant build-default -Dpackage-extra=false
}

py_test()
{
    ant -f components/tools/OmeroPy/build.xml test -Dtest.with.fail=true
    ant -f components/tools/OmeroWeb/build.xml test -Dtest.with.fail=true
    # make sure all OmeroWeb Python modules can be imported
    # (this will find invalid imports that flake8 does not check for)
    echo Checking OmeroWeb Python imports
    export PYTHONPATH=$PYTHONPATH:../target/lib/python
    ! ( cd components/tools/OmeroWeb ;
        find omeroweb -name "*.py" |
        cut -d "." -f -1 |
        grep -v __init__ |
        tr / . |
        xargs -n 1 echo import |
        tee /dev/stderr |
        python omeroweb/manage.py shell 2>&1 >/dev/null |
        grep -B2 ImportError
      )
    test $? = 0
}

for arg in "$@"
do
    case $arg in
        clean)
            clean ;;
        build-java)
            java_build && java_test ;;
        build-python)
            py_flake8 && py_build && py_test ;;
        java-build)
            java_build ;;
        java-test)
            java_test ;;
        py-flake8)
            py_flake8;;
        py-build)
            py_build ;;
        py-test)
            py_test ;;
        all)
            py_flake8 java_build java_test py_test ;;
        *)
            echo "Invalid argument: \"$arg\"" >&2
            exit 1
            ;;
    esac
done

exit 0
