#!/bin/sh
# This script is used for testing the build, primarily for use
# with travis, but may be used by hand as well.

set -e

if [ -z "$ICE_HOME" ]; then
  export ICE_HOME=/usr/share/Ice
fi

# Clean up
clean()
{
    ./build.py clean
}

build_java()
{
    TEST="-p" ./build.py build-default test-compile
    ./build.py -f components/model/build.xml test -Dtest.with.fail=true -Dtestng.useDefaultListeners=true
    ./build.py -f components/common/build.xml test -Dtest.with.fail=true -Dtestng.useDefaultListeners=true
    ./build.py -f components/rendering/build.xml test -Dtest.with.fail=true -Dtestng.useDefaultListeners=true
    ./build.py -f components/server/build.xml test -Dtest.with.fail=true -Dtestng.useDefaultListeners=true
    # Failing: dsl, romio, blitz
}

build_python()
{
    flake8 -v components/tools/OmeroPy/src
    flake8 -v components/tools/OmeroPy/test
    flake8 -v components/tools/OmeroFS/src
    flake8 -v components/tools/OmeroFS/test
    flake8 -v components/tools/OmeroWeb/omeroweb
    flake8 -v components/tools/OmeroWeb/test
    ./build.py build-default
    ./build.py -py test -Dtest.with.fail=true
    ./build.py -fs test -Dtest.with.fail=true
    ./build.py -web test -Dtest.with.fail=true
    # make sure all OmeroWeb Python modules can be imported
    # (this will find invalid imports that flake8 does not check for)
    echo Checking OmeroWeb Python imports
    export PYTHONPATH=$PYTHONPATH:../target/lib/python
    ! ( cd components/tools/OmeroWeb ;
        find omeroweb -name "*.py" |
        cut -d "." -f -1 |
        grep -v __init__ |
        tr / . |
        xargs -n 1 echo import |
        tee /dev/stderr |
        python omeroweb/manage.py shell 2>&1 >/dev/null |
        grep -B2 ImportError
      )
    test $? = 0
}

build_cpp()
{
    (
        cd components/tools/OmeroCpp
        mkdir build
        cd build
        (
            mkdir gtest
            cd gtest
            cmake /usr/src/gtest
            make
        )
        GTEST_ROOT=$(pwd)/gtest cmake ..
        make
#        make test
        make DESTDIR=../install install
#        make doc
    )
}

for arg in "$@"
do
    case $arg in
        clean)
            clean ;;
        build-java)
            build_java ;;
        build-python)
            build_python ;;
        build-cpp)
            build_cpp ;;
        *)
            echo "Invalid argument: \"$arg\"" >&2
            exit 1
            ;;
    esac
done

exit 0
