--
-- Copyright 2009 Glencoe Software, Inc. All rights reserved.
-- Use is subject to license terms supplied in LICENSE.txt
--

-- This file was generated by dsl/resources/ome/dsl/enums_update.vm

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'WideField' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'WideField') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'LaserScanningConfocalMicroscopy' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'LaserScanningConfocalMicroscopy') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'SpinningDiskConfocal' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'SpinningDiskConfocal') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'SlitScanConfocal' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'SlitScanConfocal') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'MultiPhotonMicroscopy' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'MultiPhotonMicroscopy') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'StructuredIllumination' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'StructuredIllumination') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'SingleMoleculeImaging' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'SingleMoleculeImaging') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'TotalInternalReflection' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'TotalInternalReflection') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'FluorescenceLifetime' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'FluorescenceLifetime') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'SpectralImaging' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'SpectralImaging') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'FluorescenceCorrelationSpectroscopy' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'FluorescenceCorrelationSpectroscopy') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'NearFieldScanningOpticalMicroscopy' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'NearFieldScanningOpticalMicroscopy') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'SecondHarmonicGenerationImaging' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'SecondHarmonicGenerationImaging') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'PALM' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'PALM') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'STORM' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'STORM') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'STED' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'STED') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'TIRF' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'TIRF') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'FSM' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'FSM') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'LCM' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'LCM') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'Other' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'Other') limit 1;

insert into acquisitionmode (id,permissions,value)
    select ome_nextval('seq_acquisitionmode'),-35,'Unknown' from acquisitionmode where not exists(
        select 1 from acquisitionmode where value = 'Unknown') limit 1;

insert into arctype (id,permissions,value)
    select ome_nextval('seq_arctype'),-35,'Hg' from arctype where not exists(
        select 1 from arctype where value = 'Hg') limit 1;

insert into arctype (id,permissions,value)
    select ome_nextval('seq_arctype'),-35,'Xe' from arctype where not exists(
        select 1 from arctype where value = 'Xe') limit 1;

insert into arctype (id,permissions,value)
    select ome_nextval('seq_arctype'),-35,'HgXe' from arctype where not exists(
        select 1 from arctype where value = 'HgXe') limit 1;

insert into arctype (id,permissions,value)
    select ome_nextval('seq_arctype'),-35,'Other' from arctype where not exists(
        select 1 from arctype where value = 'Other') limit 1;

insert into arctype (id,permissions,value)
    select ome_nextval('seq_arctype'),-35,'Unknown' from arctype where not exists(
        select 1 from arctype where value = 'Unknown') limit 1;

insert into binning (id,permissions,value)
    select ome_nextval('seq_binning'),-35,'1x1' from binning where not exists(
        select 1 from binning where value = '1x1') limit 1;

insert into binning (id,permissions,value)
    select ome_nextval('seq_binning'),-35,'2x2' from binning where not exists(
        select 1 from binning where value = '2x2') limit 1;

insert into binning (id,permissions,value)
    select ome_nextval('seq_binning'),-35,'4x4' from binning where not exists(
        select 1 from binning where value = '4x4') limit 1;

insert into binning (id,permissions,value)
    select ome_nextval('seq_binning'),-35,'8x8' from binning where not exists(
        select 1 from binning where value = '8x8') limit 1;

insert into checksumalgorithm (id,permissions,value)
    select ome_nextval('seq_checksumalgorithm'),-35,'Adler-32' from checksumalgorithm where not exists(
        select 1 from checksumalgorithm where value = 'Adler-32') limit 1;

insert into checksumalgorithm (id,permissions,value)
    select ome_nextval('seq_checksumalgorithm'),-35,'CRC-32' from checksumalgorithm where not exists(
        select 1 from checksumalgorithm where value = 'CRC-32') limit 1;

insert into checksumalgorithm (id,permissions,value)
    select ome_nextval('seq_checksumalgorithm'),-35,'MD5-128' from checksumalgorithm where not exists(
        select 1 from checksumalgorithm where value = 'MD5-128') limit 1;

insert into checksumalgorithm (id,permissions,value)
    select ome_nextval('seq_checksumalgorithm'),-35,'Murmur3-32' from checksumalgorithm where not exists(
        select 1 from checksumalgorithm where value = 'Murmur3-32') limit 1;

insert into checksumalgorithm (id,permissions,value)
    select ome_nextval('seq_checksumalgorithm'),-35,'Murmur3-128' from checksumalgorithm where not exists(
        select 1 from checksumalgorithm where value = 'Murmur3-128') limit 1;

insert into checksumalgorithm (id,permissions,value)
    select ome_nextval('seq_checksumalgorithm'),-35,'SHA1-160' from checksumalgorithm where not exists(
        select 1 from checksumalgorithm where value = 'SHA1-160') limit 1;

insert into checksumalgorithm (id,permissions,value)
    select ome_nextval('seq_checksumalgorithm'),-35,'File-Size-64' from checksumalgorithm where not exists(
        select 1 from checksumalgorithm where value = 'File-Size-64') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'Brightfield' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'Brightfield') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'Phase' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'Phase') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'DIC' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'DIC') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'HoffmanModulation' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'HoffmanModulation') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'ObliqueIllumination' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'ObliqueIllumination') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'PolarizedLight' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'PolarizedLight') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'Darkfield' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'Darkfield') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'Fluorescence' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'Fluorescence') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'Other' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'Other') limit 1;

insert into contrastmethod (id,permissions,value)
    select ome_nextval('seq_contrastmethod'),-35,'Unknown' from contrastmethod where not exists(
        select 1 from contrastmethod where value = 'Unknown') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'UV' from correction where not exists(
        select 1 from correction where value = 'UV') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'PlanApo' from correction where not exists(
        select 1 from correction where value = 'PlanApo') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'PlanFluor' from correction where not exists(
        select 1 from correction where value = 'PlanFluor') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'SuperFluor' from correction where not exists(
        select 1 from correction where value = 'SuperFluor') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'VioletCorrected' from correction where not exists(
        select 1 from correction where value = 'VioletCorrected') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Achro' from correction where not exists(
        select 1 from correction where value = 'Achro') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Achromat' from correction where not exists(
        select 1 from correction where value = 'Achromat') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Fluor' from correction where not exists(
        select 1 from correction where value = 'Fluor') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Fl' from correction where not exists(
        select 1 from correction where value = 'Fl') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Fluar' from correction where not exists(
        select 1 from correction where value = 'Fluar') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Neofluar' from correction where not exists(
        select 1 from correction where value = 'Neofluar') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Fluotar' from correction where not exists(
        select 1 from correction where value = 'Fluotar') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Apo' from correction where not exists(
        select 1 from correction where value = 'Apo') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Other' from correction where not exists(
        select 1 from correction where value = 'Other') limit 1;

insert into correction (id,permissions,value)
    select ome_nextval('seq_correction'),-35,'Unknown' from correction where not exists(
        select 1 from correction where value = 'Unknown') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'CCD' from detectortype where not exists(
        select 1 from detectortype where value = 'CCD') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'IntensifiedCCD' from detectortype where not exists(
        select 1 from detectortype where value = 'IntensifiedCCD') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'AnalogVideo' from detectortype where not exists(
        select 1 from detectortype where value = 'AnalogVideo') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'PMT' from detectortype where not exists(
        select 1 from detectortype where value = 'PMT') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'Photodiode' from detectortype where not exists(
        select 1 from detectortype where value = 'Photodiode') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'Spectroscopy' from detectortype where not exists(
        select 1 from detectortype where value = 'Spectroscopy') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'LifetimeImaging' from detectortype where not exists(
        select 1 from detectortype where value = 'LifetimeImaging') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'CorrelationSpectroscopy' from detectortype where not exists(
        select 1 from detectortype where value = 'CorrelationSpectroscopy') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'FTIR' from detectortype where not exists(
        select 1 from detectortype where value = 'FTIR') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'EM-CCD' from detectortype where not exists(
        select 1 from detectortype where value = 'EM-CCD') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'APD' from detectortype where not exists(
        select 1 from detectortype where value = 'APD') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'CMOS' from detectortype where not exists(
        select 1 from detectortype where value = 'CMOS') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'EBCCD' from detectortype where not exists(
        select 1 from detectortype where value = 'EBCCD') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'Other' from detectortype where not exists(
        select 1 from detectortype where value = 'Other') limit 1;

insert into detectortype (id,permissions,value)
    select ome_nextval('seq_detectortype'),-35,'Unknown' from detectortype where not exists(
        select 1 from detectortype where value = 'Unknown') limit 1;

insert into dimensionorder (id,permissions,value)
    select ome_nextval('seq_dimensionorder'),-35,'XYZCT' from dimensionorder where not exists(
        select 1 from dimensionorder where value = 'XYZCT') limit 1;

insert into dimensionorder (id,permissions,value)
    select ome_nextval('seq_dimensionorder'),-35,'XYZTC' from dimensionorder where not exists(
        select 1 from dimensionorder where value = 'XYZTC') limit 1;

insert into dimensionorder (id,permissions,value)
    select ome_nextval('seq_dimensionorder'),-35,'XYCTZ' from dimensionorder where not exists(
        select 1 from dimensionorder where value = 'XYCTZ') limit 1;

insert into dimensionorder (id,permissions,value)
    select ome_nextval('seq_dimensionorder'),-35,'XYCZT' from dimensionorder where not exists(
        select 1 from dimensionorder where value = 'XYCZT') limit 1;

insert into dimensionorder (id,permissions,value)
    select ome_nextval('seq_dimensionorder'),-35,'XYTCZ' from dimensionorder where not exists(
        select 1 from dimensionorder where value = 'XYTCZ') limit 1;

insert into dimensionorder (id,permissions,value)
    select ome_nextval('seq_dimensionorder'),-35,'XYTZC' from dimensionorder where not exists(
        select 1 from dimensionorder where value = 'XYTZC') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'Import' from eventtype where not exists(
        select 1 from eventtype where value = 'Import') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'Internal' from eventtype where not exists(
        select 1 from eventtype where value = 'Internal') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'Shoola' from eventtype where not exists(
        select 1 from eventtype where value = 'Shoola') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'User' from eventtype where not exists(
        select 1 from eventtype where value = 'User') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'Task' from eventtype where not exists(
        select 1 from eventtype where value = 'Task') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'Test' from eventtype where not exists(
        select 1 from eventtype where value = 'Test') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'Processing' from eventtype where not exists(
        select 1 from eventtype where value = 'Processing') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'FullText' from eventtype where not exists(
        select 1 from eventtype where value = 'FullText') limit 1;

insert into eventtype (id,permissions,value)
    select ome_nextval('seq_eventtype'),-35,'Sessions' from eventtype where not exists(
        select 1 from eventtype where value = 'Sessions') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'FP' from experimenttype where not exists(
        select 1 from experimenttype where value = 'FP') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'FRET' from experimenttype where not exists(
        select 1 from experimenttype where value = 'FRET') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'TimeLapse' from experimenttype where not exists(
        select 1 from experimenttype where value = 'TimeLapse') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'FourDPlus' from experimenttype where not exists(
        select 1 from experimenttype where value = 'FourDPlus') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Screen' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Screen') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Immunocytochemistry' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Immunocytochemistry') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Immunofluorescence' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Immunofluorescence') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'FISH' from experimenttype where not exists(
        select 1 from experimenttype where value = 'FISH') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Electrophysiology' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Electrophysiology') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'IonImaging' from experimenttype where not exists(
        select 1 from experimenttype where value = 'IonImaging') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Colocalization' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Colocalization') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'PGIDocumentation' from experimenttype where not exists(
        select 1 from experimenttype where value = 'PGIDocumentation') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'FluorescenceLifetime' from experimenttype where not exists(
        select 1 from experimenttype where value = 'FluorescenceLifetime') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'SpectralImaging' from experimenttype where not exists(
        select 1 from experimenttype where value = 'SpectralImaging') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Photobleaching' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Photobleaching') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Other' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Other') limit 1;

insert into experimenttype (id,permissions,value)
    select ome_nextval('seq_experimenttype'),-35,'Unknown' from experimenttype where not exists(
        select 1 from experimenttype where value = 'Unknown') limit 1;

insert into family (id,permissions,value)
    select ome_nextval('seq_family'),-35,'linear' from family where not exists(
        select 1 from family where value = 'linear') limit 1;

insert into family (id,permissions,value)
    select ome_nextval('seq_family'),-35,'polynomial' from family where not exists(
        select 1 from family where value = 'polynomial') limit 1;

insert into family (id,permissions,value)
    select ome_nextval('seq_family'),-35,'exponential' from family where not exists(
        select 1 from family where value = 'exponential') limit 1;

insert into family (id,permissions,value)
    select ome_nextval('seq_family'),-35,'logarithmic' from family where not exists(
        select 1 from family where value = 'logarithmic') limit 1;

insert into filamenttype (id,permissions,value)
    select ome_nextval('seq_filamenttype'),-35,'Incandescent' from filamenttype where not exists(
        select 1 from filamenttype where value = 'Incandescent') limit 1;

insert into filamenttype (id,permissions,value)
    select ome_nextval('seq_filamenttype'),-35,'Halogen' from filamenttype where not exists(
        select 1 from filamenttype where value = 'Halogen') limit 1;

insert into filamenttype (id,permissions,value)
    select ome_nextval('seq_filamenttype'),-35,'Other' from filamenttype where not exists(
        select 1 from filamenttype where value = 'Other') limit 1;

insert into filamenttype (id,permissions,value)
    select ome_nextval('seq_filamenttype'),-35,'Unknown' from filamenttype where not exists(
        select 1 from filamenttype where value = 'Unknown') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'LongPass' from filtertype where not exists(
        select 1 from filtertype where value = 'LongPass') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'ShortPass' from filtertype where not exists(
        select 1 from filtertype where value = 'ShortPass') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'BandPass' from filtertype where not exists(
        select 1 from filtertype where value = 'BandPass') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'MultiPass' from filtertype where not exists(
        select 1 from filtertype where value = 'MultiPass') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'Dichroic' from filtertype where not exists(
        select 1 from filtertype where value = 'Dichroic') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'NeutralDensity' from filtertype where not exists(
        select 1 from filtertype where value = 'NeutralDensity') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'Tuneable' from filtertype where not exists(
        select 1 from filtertype where value = 'Tuneable') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'Other' from filtertype where not exists(
        select 1 from filtertype where value = 'Other') limit 1;

insert into filtertype (id,permissions,value)
    select ome_nextval('seq_filtertype'),-35,'Unknown' from filtertype where not exists(
        select 1 from filtertype where value = 'Unknown') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'PNG' from format where not exists(
        select 1 from format where value = 'PNG') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/PNG' from format where not exists(
        select 1 from format where value = 'Companion/PNG') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'JPEG' from format where not exists(
        select 1 from format where value = 'JPEG') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/JPEG' from format where not exists(
        select 1 from format where value = 'Companion/JPEG') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'PGM' from format where not exists(
        select 1 from format where value = 'PGM') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/PGM' from format where not exists(
        select 1 from format where value = 'Companion/PGM') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Fits' from format where not exists(
        select 1 from format where value = 'Fits') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Fits' from format where not exists(
        select 1 from format where value = 'Companion/Fits') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'GIF' from format where not exists(
        select 1 from format where value = 'GIF') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/GIF' from format where not exists(
        select 1 from format where value = 'Companion/GIF') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'BMP' from format where not exists(
        select 1 from format where value = 'BMP') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/BMP' from format where not exists(
        select 1 from format where value = 'Companion/BMP') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Dicom' from format where not exists(
        select 1 from format where value = 'Dicom') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Dicom' from format where not exists(
        select 1 from format where value = 'Companion/Dicom') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'BioRad' from format where not exists(
        select 1 from format where value = 'BioRad') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/BioRad' from format where not exists(
        select 1 from format where value = 'Companion/BioRad') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'IPLab' from format where not exists(
        select 1 from format where value = 'IPLab') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/IPLab' from format where not exists(
        select 1 from format where value = 'Companion/IPLab') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Deltavision' from format where not exists(
        select 1 from format where value = 'Deltavision') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Deltavision' from format where not exists(
        select 1 from format where value = 'Companion/Deltavision') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'MRC' from format where not exists(
        select 1 from format where value = 'MRC') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/MRC' from format where not exists(
        select 1 from format where value = 'Companion/MRC') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Gatan' from format where not exists(
        select 1 from format where value = 'Gatan') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Gatan' from format where not exists(
        select 1 from format where value = 'Companion/Gatan') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Imaris' from format where not exists(
        select 1 from format where value = 'Imaris') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Imaris' from format where not exists(
        select 1 from format where value = 'Companion/Imaris') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'OpenlabRaw' from format where not exists(
        select 1 from format where value = 'OpenlabRaw') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/OpenlabRaw' from format where not exists(
        select 1 from format where value = 'Companion/OpenlabRaw') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'OMEXML' from format where not exists(
        select 1 from format where value = 'OMEXML') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/OMEXML' from format where not exists(
        select 1 from format where value = 'Companion/OMEXML') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'LIF' from format where not exists(
        select 1 from format where value = 'LIF') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/LIF' from format where not exists(
        select 1 from format where value = 'Companion/LIF') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'AVI' from format where not exists(
        select 1 from format where value = 'AVI') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/AVI' from format where not exists(
        select 1 from format where value = 'Companion/AVI') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'QT' from format where not exists(
        select 1 from format where value = 'QT') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/QT' from format where not exists(
        select 1 from format where value = 'Companion/QT') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Pict' from format where not exists(
        select 1 from format where value = 'Pict') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Pict' from format where not exists(
        select 1 from format where value = 'Companion/Pict') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'SDT' from format where not exists(
        select 1 from format where value = 'SDT') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/SDT' from format where not exists(
        select 1 from format where value = 'Companion/SDT') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'EPS' from format where not exists(
        select 1 from format where value = 'EPS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/EPS' from format where not exists(
        select 1 from format where value = 'Companion/EPS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Slidebook' from format where not exists(
        select 1 from format where value = 'Slidebook') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Slidebook' from format where not exists(
        select 1 from format where value = 'Companion/Slidebook') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Alicona' from format where not exists(
        select 1 from format where value = 'Alicona') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Alicona' from format where not exists(
        select 1 from format where value = 'Companion/Alicona') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'MNG' from format where not exists(
        select 1 from format where value = 'MNG') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/MNG' from format where not exists(
        select 1 from format where value = 'Companion/MNG') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'NRRD' from format where not exists(
        select 1 from format where value = 'NRRD') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/NRRD' from format where not exists(
        select 1 from format where value = 'Companion/NRRD') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Khoros' from format where not exists(
        select 1 from format where value = 'Khoros') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Khoros' from format where not exists(
        select 1 from format where value = 'Companion/Khoros') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Visitech' from format where not exists(
        select 1 from format where value = 'Visitech') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Visitech' from format where not exists(
        select 1 from format where value = 'Companion/Visitech') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'LIM' from format where not exists(
        select 1 from format where value = 'LIM') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/LIM' from format where not exists(
        select 1 from format where value = 'Companion/LIM') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'PSD' from format where not exists(
        select 1 from format where value = 'PSD') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/PSD' from format where not exists(
        select 1 from format where value = 'Companion/PSD') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'InCell' from format where not exists(
        select 1 from format where value = 'InCell') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/InCell' from format where not exists(
        select 1 from format where value = 'Companion/InCell') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'ICS' from format where not exists(
        select 1 from format where value = 'ICS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/ICS' from format where not exists(
        select 1 from format where value = 'Companion/ICS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'PerkinElmer' from format where not exists(
        select 1 from format where value = 'PerkinElmer') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/PerkinElmer' from format where not exists(
        select 1 from format where value = 'Companion/PerkinElmer') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'TCS' from format where not exists(
        select 1 from format where value = 'TCS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/TCS' from format where not exists(
        select 1 from format where value = 'Companion/TCS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'FV1000' from format where not exists(
        select 1 from format where value = 'FV1000') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/FV1000' from format where not exists(
        select 1 from format where value = 'Companion/FV1000') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'ZeissZVI' from format where not exists(
        select 1 from format where value = 'ZeissZVI') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/ZeissZVI' from format where not exists(
        select 1 from format where value = 'Companion/ZeissZVI') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'IPW' from format where not exists(
        select 1 from format where value = 'IPW') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/IPW' from format where not exists(
        select 1 from format where value = 'Companion/IPW') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'LegacyND2' from format where not exists(
        select 1 from format where value = 'LegacyND2') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/LegacyND2' from format where not exists(
        select 1 from format where value = 'Companion/LegacyND2') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'ND2' from format where not exists(
        select 1 from format where value = 'ND2') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/ND2' from format where not exists(
        select 1 from format where value = 'Companion/ND2') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'PCI' from format where not exists(
        select 1 from format where value = 'PCI') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/PCI' from format where not exists(
        select 1 from format where value = 'Companion/PCI') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'ImarisHDF' from format where not exists(
        select 1 from format where value = 'ImarisHDF') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/ImarisHDF' from format where not exists(
        select 1 from format where value = 'Companion/ImarisHDF') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Metamorph' from format where not exists(
        select 1 from format where value = 'Metamorph') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Metamorph' from format where not exists(
        select 1 from format where value = 'Companion/Metamorph') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'ZeissLSM' from format where not exists(
        select 1 from format where value = 'ZeissLSM') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/ZeissLSM' from format where not exists(
        select 1 from format where value = 'Companion/ZeissLSM') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'SEQ' from format where not exists(
        select 1 from format where value = 'SEQ') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/SEQ' from format where not exists(
        select 1 from format where value = 'Companion/SEQ') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Gel' from format where not exists(
        select 1 from format where value = 'Gel') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Gel' from format where not exists(
        select 1 from format where value = 'Companion/Gel') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'ImarisTiff' from format where not exists(
        select 1 from format where value = 'ImarisTiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/ImarisTiff' from format where not exists(
        select 1 from format where value = 'Companion/ImarisTiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Flex' from format where not exists(
        select 1 from format where value = 'Flex') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Flex' from format where not exists(
        select 1 from format where value = 'Companion/Flex') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'SVS' from format where not exists(
        select 1 from format where value = 'SVS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/SVS' from format where not exists(
        select 1 from format where value = 'Companion/SVS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Leica' from format where not exists(
        select 1 from format where value = 'Leica') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Leica' from format where not exists(
        select 1 from format where value = 'Companion/Leica') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Nikon' from format where not exists(
        select 1 from format where value = 'Nikon') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Nikon' from format where not exists(
        select 1 from format where value = 'Companion/Nikon') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Fluoview' from format where not exists(
        select 1 from format where value = 'Fluoview') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Fluoview' from format where not exists(
        select 1 from format where value = 'Companion/Fluoview') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Prairie' from format where not exists(
        select 1 from format where value = 'Prairie') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Prairie' from format where not exists(
        select 1 from format where value = 'Companion/Prairie') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Micromanager' from format where not exists(
        select 1 from format where value = 'Micromanager') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Micromanager' from format where not exists(
        select 1 from format where value = 'Companion/Micromanager') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'ImprovisionTiff' from format where not exists(
        select 1 from format where value = 'ImprovisionTiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/ImprovisionTiff' from format where not exists(
        select 1 from format where value = 'Companion/ImprovisionTiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'OMETiff' from format where not exists(
        select 1 from format where value = 'OMETiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/OMETiff' from format where not exists(
        select 1 from format where value = 'Companion/OMETiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'MetamorphTiff' from format where not exists(
        select 1 from format where value = 'MetamorphTiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/MetamorphTiff' from format where not exists(
        select 1 from format where value = 'Companion/MetamorphTiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Tiff' from format where not exists(
        select 1 from format where value = 'Tiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Tiff' from format where not exists(
        select 1 from format where value = 'Companion/Tiff') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Openlab' from format where not exists(
        select 1 from format where value = 'Openlab') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/Openlab' from format where not exists(
        select 1 from format where value = 'Companion/Openlab') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'MIAS' from format where not exists(
        select 1 from format where value = 'MIAS') limit 1;

insert into format (id,permissions,value)
    select ome_nextval('seq_format'),-35,'Companion/MIAS' from format where not exists(
        select 1 from format where value = 'Companion/MIAS') limit 1;

insert into illumination (id,permissions,value)
    select ome_nextval('seq_illumination'),-35,'Transmitted' from illumination where not exists(
        select 1 from illumination where value = 'Transmitted') limit 1;

insert into illumination (id,permissions,value)
    select ome_nextval('seq_illumination'),-35,'Epifluorescence' from illumination where not exists(
        select 1 from illumination where value = 'Epifluorescence') limit 1;

insert into illumination (id,permissions,value)
    select ome_nextval('seq_illumination'),-35,'Oblique' from illumination where not exists(
        select 1 from illumination where value = 'Oblique') limit 1;

insert into illumination (id,permissions,value)
    select ome_nextval('seq_illumination'),-35,'NonLinear' from illumination where not exists(
        select 1 from illumination where value = 'NonLinear') limit 1;

insert into illumination (id,permissions,value)
    select ome_nextval('seq_illumination'),-35,'Other' from illumination where not exists(
        select 1 from illumination where value = 'Other') limit 1;

insert into illumination (id,permissions,value)
    select ome_nextval('seq_illumination'),-35,'Unknown' from illumination where not exists(
        select 1 from illumination where value = 'Unknown') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'Oil' from immersion where not exists(
        select 1 from immersion where value = 'Oil') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'Water' from immersion where not exists(
        select 1 from immersion where value = 'Water') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'WaterDipping' from immersion where not exists(
        select 1 from immersion where value = 'WaterDipping') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'Air' from immersion where not exists(
        select 1 from immersion where value = 'Air') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'Multi' from immersion where not exists(
        select 1 from immersion where value = 'Multi') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'Glycerol' from immersion where not exists(
        select 1 from immersion where value = 'Glycerol') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'Other' from immersion where not exists(
        select 1 from immersion where value = 'Other') limit 1;

insert into immersion (id,permissions,value)
    select ome_nextval('seq_immersion'),-35,'Unknown' from immersion where not exists(
        select 1 from immersion where value = 'Unknown') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Submitted' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Submitted') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Resubmitted' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Resubmitted') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Queued' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Queued') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Requeued' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Requeued') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Running' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Running') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Error' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Error') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Waiting' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Waiting') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Finished' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Finished') limit 1;

insert into jobstatus (id,permissions,value)
    select ome_nextval('seq_jobstatus'),-35,'Cancelled' from jobstatus where not exists(
        select 1 from jobstatus where value = 'Cancelled') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Rhodamine6G' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Rhodamine6G') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'CoumarinC30' from lasermedium where not exists(
        select 1 from lasermedium where value = 'CoumarinC30') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'ArFl' from lasermedium where not exists(
        select 1 from lasermedium where value = 'ArFl') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'ArCl' from lasermedium where not exists(
        select 1 from lasermedium where value = 'ArCl') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'KrFl' from lasermedium where not exists(
        select 1 from lasermedium where value = 'KrFl') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'KrCl' from lasermedium where not exists(
        select 1 from lasermedium where value = 'KrCl') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'XeFl' from lasermedium where not exists(
        select 1 from lasermedium where value = 'XeFl') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'XeCl' from lasermedium where not exists(
        select 1 from lasermedium where value = 'XeCl') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'XeBr' from lasermedium where not exists(
        select 1 from lasermedium where value = 'XeBr') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'GaAs' from lasermedium where not exists(
        select 1 from lasermedium where value = 'GaAs') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'GaAlAs' from lasermedium where not exists(
        select 1 from lasermedium where value = 'GaAlAs') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'EMinus' from lasermedium where not exists(
        select 1 from lasermedium where value = 'EMinus') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Cu' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Cu') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Ag' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Ag') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'N' from lasermedium where not exists(
        select 1 from lasermedium where value = 'N') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Ar' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Ar') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Kr' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Kr') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Xe' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Xe') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'HeNe' from lasermedium where not exists(
        select 1 from lasermedium where value = 'HeNe') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'HeCd' from lasermedium where not exists(
        select 1 from lasermedium where value = 'HeCd') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'CO' from lasermedium where not exists(
        select 1 from lasermedium where value = 'CO') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'CO2' from lasermedium where not exists(
        select 1 from lasermedium where value = 'CO2') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'H2O' from lasermedium where not exists(
        select 1 from lasermedium where value = 'H2O') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'HFl' from lasermedium where not exists(
        select 1 from lasermedium where value = 'HFl') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'NdGlass' from lasermedium where not exists(
        select 1 from lasermedium where value = 'NdGlass') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'NdYAG' from lasermedium where not exists(
        select 1 from lasermedium where value = 'NdYAG') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'ErGlass' from lasermedium where not exists(
        select 1 from lasermedium where value = 'ErGlass') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'ErYAG' from lasermedium where not exists(
        select 1 from lasermedium where value = 'ErYAG') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'HoYLF' from lasermedium where not exists(
        select 1 from lasermedium where value = 'HoYLF') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'HoYAG' from lasermedium where not exists(
        select 1 from lasermedium where value = 'HoYAG') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Ruby' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Ruby') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'TiSapphire' from lasermedium where not exists(
        select 1 from lasermedium where value = 'TiSapphire') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Alexandrite' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Alexandrite') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Other' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Other') limit 1;

insert into lasermedium (id,permissions,value)
    select ome_nextval('seq_lasermedium'),-35,'Unknown' from lasermedium where not exists(
        select 1 from lasermedium where value = 'Unknown') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'Excimer' from lasertype where not exists(
        select 1 from lasertype where value = 'Excimer') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'Gas' from lasertype where not exists(
        select 1 from lasertype where value = 'Gas') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'MetalVapor' from lasertype where not exists(
        select 1 from lasertype where value = 'MetalVapor') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'SolidState' from lasertype where not exists(
        select 1 from lasertype where value = 'SolidState') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'Dye' from lasertype where not exists(
        select 1 from lasertype where value = 'Dye') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'Semiconductor' from lasertype where not exists(
        select 1 from lasertype where value = 'Semiconductor') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'FreeElectron' from lasertype where not exists(
        select 1 from lasertype where value = 'FreeElectron') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'Other' from lasertype where not exists(
        select 1 from lasertype where value = 'Other') limit 1;

insert into lasertype (id,permissions,value)
    select ome_nextval('seq_lasertype'),-35,'Unknown' from lasertype where not exists(
        select 1 from lasertype where value = 'Unknown') limit 1;

insert into medium (id,permissions,value)
    select ome_nextval('seq_medium'),-35,'Air' from medium where not exists(
        select 1 from medium where value = 'Air') limit 1;

insert into medium (id,permissions,value)
    select ome_nextval('seq_medium'),-35,'Oil' from medium where not exists(
        select 1 from medium where value = 'Oil') limit 1;

insert into medium (id,permissions,value)
    select ome_nextval('seq_medium'),-35,'Water' from medium where not exists(
        select 1 from medium where value = 'Water') limit 1;

insert into medium (id,permissions,value)
    select ome_nextval('seq_medium'),-35,'Glycerol' from medium where not exists(
        select 1 from medium where value = 'Glycerol') limit 1;

insert into medium (id,permissions,value)
    select ome_nextval('seq_medium'),-35,'Other' from medium where not exists(
        select 1 from medium where value = 'Other') limit 1;

insert into medium (id,permissions,value)
    select ome_nextval('seq_medium'),-35,'Unknown' from medium where not exists(
        select 1 from medium where value = 'Unknown') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'FRAP' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'FRAP') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'Photoablation' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'Photoablation') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'Photoactivation' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'Photoactivation') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'Uncaging' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'Uncaging') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'OpticalTrapping' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'OpticalTrapping') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'FLIP' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'FLIP') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'InverseFRAP' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'InverseFRAP') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'Other' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'Other') limit 1;

insert into microbeammanipulationtype (id,permissions,value)
    select ome_nextval('seq_microbeammanipulationtype'),-35,'Unknown' from microbeammanipulationtype where not exists(
        select 1 from microbeammanipulationtype where value = 'Unknown') limit 1;

insert into microscopetype (id,permissions,value)
    select ome_nextval('seq_microscopetype'),-35,'Upright' from microscopetype where not exists(
        select 1 from microscopetype where value = 'Upright') limit 1;

insert into microscopetype (id,permissions,value)
    select ome_nextval('seq_microscopetype'),-35,'Inverted' from microscopetype where not exists(
        select 1 from microscopetype where value = 'Inverted') limit 1;

insert into microscopetype (id,permissions,value)
    select ome_nextval('seq_microscopetype'),-35,'Dissection' from microscopetype where not exists(
        select 1 from microscopetype where value = 'Dissection') limit 1;

insert into microscopetype (id,permissions,value)
    select ome_nextval('seq_microscopetype'),-35,'Electrophysiology' from microscopetype where not exists(
        select 1 from microscopetype where value = 'Electrophysiology') limit 1;

insert into microscopetype (id,permissions,value)
    select ome_nextval('seq_microscopetype'),-35,'Other' from microscopetype where not exists(
        select 1 from microscopetype where value = 'Other') limit 1;

insert into microscopetype (id,permissions,value)
    select ome_nextval('seq_microscopetype'),-35,'Unknown' from microscopetype where not exists(
        select 1 from microscopetype where value = 'Unknown') limit 1;

insert into photometricinterpretation (id,permissions,value)
    select ome_nextval('seq_photometricinterpretation'),-35,'RGB' from photometricinterpretation where not exists(
        select 1 from photometricinterpretation where value = 'RGB') limit 1;

insert into photometricinterpretation (id,permissions,value)
    select ome_nextval('seq_photometricinterpretation'),-35,'ARGB' from photometricinterpretation where not exists(
        select 1 from photometricinterpretation where value = 'ARGB') limit 1;

insert into photometricinterpretation (id,permissions,value)
    select ome_nextval('seq_photometricinterpretation'),-35,'CMYK' from photometricinterpretation where not exists(
        select 1 from photometricinterpretation where value = 'CMYK') limit 1;

insert into photometricinterpretation (id,permissions,value)
    select ome_nextval('seq_photometricinterpretation'),-35,'HSV' from photometricinterpretation where not exists(
        select 1 from photometricinterpretation where value = 'HSV') limit 1;

insert into photometricinterpretation (id,permissions,value)
    select ome_nextval('seq_photometricinterpretation'),-35,'Monochrome' from photometricinterpretation where not exists(
        select 1 from photometricinterpretation where value = 'Monochrome') limit 1;

insert into photometricinterpretation (id,permissions,value)
    select ome_nextval('seq_photometricinterpretation'),-35,'ColorMap' from photometricinterpretation where not exists(
        select 1 from photometricinterpretation where value = 'ColorMap') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'bit' from pixelstype where not exists(
        select 1 from pixelstype where value = 'bit') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'int8' from pixelstype where not exists(
        select 1 from pixelstype where value = 'int8') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'int16' from pixelstype where not exists(
        select 1 from pixelstype where value = 'int16') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'int32' from pixelstype where not exists(
        select 1 from pixelstype where value = 'int32') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'uint8' from pixelstype where not exists(
        select 1 from pixelstype where value = 'uint8') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'uint16' from pixelstype where not exists(
        select 1 from pixelstype where value = 'uint16') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'uint32' from pixelstype where not exists(
        select 1 from pixelstype where value = 'uint32') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'float' from pixelstype where not exists(
        select 1 from pixelstype where value = 'float') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'double' from pixelstype where not exists(
        select 1 from pixelstype where value = 'double') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'complex' from pixelstype where not exists(
        select 1 from pixelstype where value = 'complex') limit 1;

insert into pixelstype (id,permissions,value)
    select ome_nextval('seq_pixelstype'),-35,'double-complex' from pixelstype where not exists(
        select 1 from pixelstype where value = 'double-complex') limit 1;

insert into pulse (id,permissions,value)
    select ome_nextval('seq_pulse'),-35,'CW' from pulse where not exists(
        select 1 from pulse where value = 'CW') limit 1;

insert into pulse (id,permissions,value)
    select ome_nextval('seq_pulse'),-35,'Single' from pulse where not exists(
        select 1 from pulse where value = 'Single') limit 1;

insert into pulse (id,permissions,value)
    select ome_nextval('seq_pulse'),-35,'QSwitched' from pulse where not exists(
        select 1 from pulse where value = 'QSwitched') limit 1;

insert into pulse (id,permissions,value)
    select ome_nextval('seq_pulse'),-35,'Repetitive' from pulse where not exists(
        select 1 from pulse where value = 'Repetitive') limit 1;

insert into pulse (id,permissions,value)
    select ome_nextval('seq_pulse'),-35,'ModeLocked' from pulse where not exists(
        select 1 from pulse where value = 'ModeLocked') limit 1;

insert into pulse (id,permissions,value)
    select ome_nextval('seq_pulse'),-35,'Other' from pulse where not exists(
        select 1 from pulse where value = 'Other') limit 1;

insert into pulse (id,permissions,value)
    select ome_nextval('seq_pulse'),-35,'Unknown' from pulse where not exists(
        select 1 from pulse where value = 'Unknown') limit 1;

insert into renderingmodel (id,permissions,value)
    select ome_nextval('seq_renderingmodel'),-35,'rgb' from renderingmodel where not exists(
        select 1 from renderingmodel where value = 'rgb') limit 1;

insert into renderingmodel (id,permissions,value)
    select ome_nextval('seq_renderingmodel'),-35,'greyscale' from renderingmodel where not exists(
        select 1 from renderingmodel where value = 'greyscale') limit 1;

