package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;


import java.util.*;




/**
 * AnalysisNodeExecution generated by hbm2java
 */
public class
AnalysisNodeExecution 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel {

    // Fields    

     private Integer analysisNodeExecutionId;
     private AnalysisChainExecution analysisChainExecution;
     private AnalysisChainNode analysisChainNode;
     private ModuleExecution moduleExecution;


    // Constructors

    /** default constructor */
    public AnalysisNodeExecution() {
    }
    
    /** constructor with id */
    public AnalysisNodeExecution(Integer analysisNodeExecutionId) {
        this.analysisNodeExecutionId = analysisNodeExecutionId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getAnalysisNodeExecutionId() {
        return this.analysisNodeExecutionId;
    }
    
    public void setAnalysisNodeExecutionId(Integer analysisNodeExecutionId) {
        this.analysisNodeExecutionId = analysisNodeExecutionId;
    }

    /**
     * 
     */
    public AnalysisChainExecution getAnalysisChainExecution() {
        return this.analysisChainExecution;
    }
    
    public void setAnalysisChainExecution(AnalysisChainExecution analysisChainExecution) {
        this.analysisChainExecution = analysisChainExecution;
    }

    /**
     * 
     */
    public AnalysisChainNode getAnalysisChainNode() {
        return this.analysisChainNode;
    }
    
    public void setAnalysisChainNode(AnalysisChainNode analysisChainNode) {
        this.analysisChainNode = analysisChainNode;
    }

    /**
     * 
     */
    public ModuleExecution getModuleExecution() {
        return this.moduleExecution;
    }
    
    public void setModuleExecution(ModuleExecution moduleExecution) {
        this.moduleExecution = moduleExecution;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
