package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;


import java.util.*;




/**
 * DisplayOption generated by hbm2java
 */
public class
DisplayOption 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel {

    // Fields    

     private Integer attributeId;
     private Boolean redOn;
     private Integer ZStart;
     private Boolean blueOn;
     private String colorMap;
     private Integer ZStop;
     private Float zoom;
     private Integer TStop;
     private Integer TStart;
     private Boolean greenOn;
     private Boolean displayRgb;
     private Image image;
     private ImagePixel imagePixel;
     private ModuleExecution moduleExecution;
     private Set displayRois;


    // Constructors

    /** default constructor */
    public DisplayOption() {
    }
    
    /** constructor with id */
    public DisplayOption(Integer attributeId) {
        this.attributeId = attributeId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getAttributeId() {
        return this.attributeId;
    }
    
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * 
     */
    public Boolean getRedOn() {
        return this.redOn;
    }
    
    public void setRedOn(Boolean redOn) {
        this.redOn = redOn;
    }

    /**
     * 
     */
    public Integer getZStart() {
        return this.ZStart;
    }
    
    public void setZStart(Integer ZStart) {
        this.ZStart = ZStart;
    }

    /**
     * 
     */
    public Boolean getBlueOn() {
        return this.blueOn;
    }
    
    public void setBlueOn(Boolean blueOn) {
        this.blueOn = blueOn;
    }

    /**
     * 
     */
    public String getColorMap() {
        return this.colorMap;
    }
    
    public void setColorMap(String colorMap) {
        this.colorMap = colorMap;
    }

    /**
     * 
     */
    public Integer getZStop() {
        return this.ZStop;
    }
    
    public void setZStop(Integer ZStop) {
        this.ZStop = ZStop;
    }

    /**
     * 
     */
    public Float getZoom() {
        return this.zoom;
    }
    
    public void setZoom(Float zoom) {
        this.zoom = zoom;
    }

    /**
     * 
     */
    public Integer getTStop() {
        return this.TStop;
    }
    
    public void setTStop(Integer TStop) {
        this.TStop = TStop;
    }

    /**
     * 
     */
    public Integer getTStart() {
        return this.TStart;
    }
    
    public void setTStart(Integer TStart) {
        this.TStart = TStart;
    }

    /**
     * 
     */
    public Boolean getGreenOn() {
        return this.greenOn;
    }
    
    public void setGreenOn(Boolean greenOn) {
        this.greenOn = greenOn;
    }

    /**
     * 
     */
    public Boolean getDisplayRgb() {
        return this.displayRgb;
    }
    
    public void setDisplayRgb(Boolean displayRgb) {
        this.displayRgb = displayRgb;
    }

    /**
     * 
     */
    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }

    /**
     * 
     */
    public ImagePixel getImagePixel() {
        return this.imagePixel;
    }
    
    public void setImagePixel(ImagePixel imagePixel) {
        this.imagePixel = imagePixel;
    }

    /**
     * 
     */
    public ModuleExecution getModuleExecution() {
        return this.moduleExecution;
    }
    
    public void setModuleExecution(ModuleExecution moduleExecution) {
        this.moduleExecution = moduleExecution;
    }

    /**
     * 
     */
    public Set getDisplayRois() {
        return this.displayRois;
    }
    
    public void setDisplayRois(Set displayRois) {
        this.displayRois = displayRois;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
