package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;


import java.util.*;




/**
 * FormalInput generated by hbm2java
 */
public class
FormalInput 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel {

    // Fields    

     private Integer formalInputId;
     private Boolean userDefined;
     private String name;
     private Boolean optional;
     private String description;
     private Boolean list;
     private Module module;
     private SemanticType semanticType;
     private Set analysisChainLinks;


    // Constructors

    /** default constructor */
    public FormalInput() {
    }
    
    /** constructor with id */
    public FormalInput(Integer formalInputId) {
        this.formalInputId = formalInputId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getFormalInputId() {
        return this.formalInputId;
    }
    
    public void setFormalInputId(Integer formalInputId) {
        this.formalInputId = formalInputId;
    }

    /**
     * 
     */
    public Boolean getUserDefined() {
        return this.userDefined;
    }
    
    public void setUserDefined(Boolean userDefined) {
        this.userDefined = userDefined;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public Boolean getOptional() {
        return this.optional;
    }
    
    public void setOptional(Boolean optional) {
        this.optional = optional;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public Boolean getList() {
        return this.list;
    }
    
    public void setList(Boolean list) {
        this.list = list;
    }

    /**
     * 
     */
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

    /**
     * 
     */
    public SemanticType getSemanticType() {
        return this.semanticType;
    }
    
    public void setSemanticType(SemanticType semanticType) {
        this.semanticType = semanticType;
    }

    /**
     * 
     */
    public Set getAnalysisChainLinks() {
        return this.analysisChainLinks;
    }
    
    public void setAnalysisChainLinks(Set analysisChainLinks) {
        this.analysisChainLinks = analysisChainLinks;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
