package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;


import java.util.*;




/**
 * ImagePixel generated by hbm2java
 */
public class
ImagePixel 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel {

    // Fields    

     private Integer attributeId;
     private String pixelType;
     private Integer sizeY;
     private Integer sizeZ;
     private String fileSha1;
     private String path;
     private Integer sizeT;
     private Long imageServerId;
     private Integer sizeX;
     private Integer sizeC;
     private Integer bitsPerPixel;
     private Image image;
     private Repository repository;
     private Set images;
     private Set displayOptions;
     private Set channelComponents;
     private ModuleExecution moduleExecution;


    // Constructors

    /** default constructor */
    public ImagePixel() {
    }
    
    /** constructor with id */
    public ImagePixel(Integer attributeId) {
        this.attributeId = attributeId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getAttributeId() {
        return this.attributeId;
    }
    
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * 
     */
    public String getPixelType() {
        return this.pixelType;
    }
    
    public void setPixelType(String pixelType) {
        this.pixelType = pixelType;
    }

    /**
     * 
     */
    public Integer getSizeY() {
        return this.sizeY;
    }
    
    public void setSizeY(Integer sizeY) {
        this.sizeY = sizeY;
    }

    /**
     * 
     */
    public Integer getSizeZ() {
        return this.sizeZ;
    }
    
    public void setSizeZ(Integer sizeZ) {
        this.sizeZ = sizeZ;
    }

    /**
     * 
     */
    public String getFileSha1() {
        return this.fileSha1;
    }
    
    public void setFileSha1(String fileSha1) {
        this.fileSha1 = fileSha1;
    }

    /**
     * 
     */
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * 
     */
    public Integer getSizeT() {
        return this.sizeT;
    }
    
    public void setSizeT(Integer sizeT) {
        this.sizeT = sizeT;
    }

    /**
     * 
     */
    public Long getImageServerId() {
        return this.imageServerId;
    }
    
    public void setImageServerId(Long imageServerId) {
        this.imageServerId = imageServerId;
    }

    /**
     * 
     */
    public Integer getSizeX() {
        return this.sizeX;
    }
    
    public void setSizeX(Integer sizeX) {
        this.sizeX = sizeX;
    }

    /**
     * 
     */
    public Integer getSizeC() {
        return this.sizeC;
    }
    
    public void setSizeC(Integer sizeC) {
        this.sizeC = sizeC;
    }

    /**
     * 
     */
    public Integer getBitsPerPixel() {
        return this.bitsPerPixel;
    }
    
    public void setBitsPerPixel(Integer bitsPerPixel) {
        this.bitsPerPixel = bitsPerPixel;
    }

    /**
     * 
     */
    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }

    /**
     * 
     */
    public Repository getRepository() {
        return this.repository;
    }
    
    public void setRepository(Repository repository) {
        this.repository = repository;
    }

    /**
     * 
     */
    public Set getImages() {
        return this.images;
    }
    
    public void setImages(Set images) {
        this.images = images;
    }

    /**
     * 
     */
    public Set getDisplayOptions() {
        return this.displayOptions;
    }
    
    public void setDisplayOptions(Set displayOptions) {
        this.displayOptions = displayOptions;
    }

    /**
     * 
     */
    public Set getChannelComponents() {
        return this.channelComponents;
    }
    
    public void setChannelComponents(Set channelComponents) {
        this.channelComponents = channelComponents;
    }

    /**
     * 
     */
    public ModuleExecution getModuleExecution() {
        return this.moduleExecution;
    }
    
    public void setModuleExecution(ModuleExecution moduleExecution) {
        this.moduleExecution = moduleExecution;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
