package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;


import java.util.*;




/**
 * Module generated by hbm2java
 */
public class
Module 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel {

    // Fields    

     private Integer moduleId;
     private String location;
     private String name;
     private String executionInstructions;
     private String description;
     private String moduleType;
     private String defaultIterator;
     private String newFeatureTag;
     private Set formalOutputs;
     private Set formalInputs;
     private Set moduleExecutions;
     private Set analysisChainNodes;


    // Constructors

    /** default constructor */
    public Module() {
    }
    
    /** constructor with id */
    public Module(Integer moduleId) {
        this.moduleId = moduleId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * 
     */
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getExecutionInstructions() {
        return this.executionInstructions;
    }
    
    public void setExecutionInstructions(String executionInstructions) {
        this.executionInstructions = executionInstructions;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public String getModuleType() {
        return this.moduleType;
    }
    
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * 
     */
    public String getDefaultIterator() {
        return this.defaultIterator;
    }
    
    public void setDefaultIterator(String defaultIterator) {
        this.defaultIterator = defaultIterator;
    }

    /**
     * 
     */
    public String getNewFeatureTag() {
        return this.newFeatureTag;
    }
    
    public void setNewFeatureTag(String newFeatureTag) {
        this.newFeatureTag = newFeatureTag;
    }

    /**
     * 
     */
    public Set getFormalOutputs() {
        return this.formalOutputs;
    }
    
    public void setFormalOutputs(Set formalOutputs) {
        this.formalOutputs = formalOutputs;
    }

    /**
     * 
     */
    public Set getFormalInputs() {
        return this.formalInputs;
    }
    
    public void setFormalInputs(Set formalInputs) {
        this.formalInputs = formalInputs;
    }

    /**
     * 
     */
    public Set getModuleExecutions() {
        return this.moduleExecutions;
    }
    
    public void setModuleExecutions(Set moduleExecutions) {
        this.moduleExecutions = moduleExecutions;
    }

    /**
     * 
     */
    public Set getAnalysisChainNodes() {
        return this.analysisChainNodes;
    }
    
    public void setAnalysisChainNodes(Set analysisChainNodes) {
        this.analysisChainNodes = analysisChainNodes;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
