package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;


import java.util.*;




/**
 * OmeSession generated by hbm2java
 */
public class
OmeSession 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel {

    // Fields    

     private Integer sessionId;
     private String sessionKey;
     private Integer moduleExecutionId;
     private String featureView;
     private String host;
     private Date lastAccess;
     private Date started;
     private String imageView;
     private Project project;
     private Dataset dataset;
     private Experimenter experimenter;


    // Constructors

    /** default constructor */
    public OmeSession() {
    }
    
    /** constructor with id */
    public OmeSession(Integer sessionId) {
        this.sessionId = sessionId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * 
     */
    public String getSessionKey() {
        return this.sessionKey;
    }
    
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    /**
     * 
     */
    public Integer getModuleExecutionId() {
        return this.moduleExecutionId;
    }
    
    public void setModuleExecutionId(Integer moduleExecutionId) {
        this.moduleExecutionId = moduleExecutionId;
    }

    /**
     * 
     */
    public String getFeatureView() {
        return this.featureView;
    }
    
    public void setFeatureView(String featureView) {
        this.featureView = featureView;
    }

    /**
     * 
     */
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * 
     */
    public Date getLastAccess() {
        return this.lastAccess;
    }
    
    public void setLastAccess(Date lastAccess) {
        this.lastAccess = lastAccess;
    }

    /**
     * 
     */
    public Date getStarted() {
        return this.started;
    }
    
    public void setStarted(Date started) {
        this.started = started;
    }

    /**
     * 
     */
    public String getImageView() {
        return this.imageView;
    }
    
    public void setImageView(String imageView) {
        this.imageView = imageView;
    }

    /**
     * 
     */
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * 
     */
    public Dataset getDataset() {
        return this.dataset;
    }
    
    public void setDataset(Dataset dataset) {
        this.dataset = dataset;
    }

    /**
     * 
     */
    public Experimenter getExperimenter() {
        return this.experimenter;
    }
    
    public void setExperimenter(Experimenter experimenter) {
        this.experimenter = experimenter;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
