package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;
import ome.util.Filterable;
import ome.util.Filter;


import java.util.*;




/**
 * OmeSession generated by hbm2java
 */
public class
OmeSession 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer sessionId;
     private String sessionKey;
     private Integer moduleExecutionId;
     private String featureView;
     private String host;
     private Date lastAccess;
     private Date started;
     private String imageView;
     private Project project;
     private Dataset dataset;
     private Experimenter experimenter;


    // Constructors

    /** default constructor */
    public OmeSession() {
    }
    
    /** constructor with id */
    public OmeSession(Integer sessionId) {
        this.sessionId = sessionId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * 
     */
    public String getSessionKey() {
        return this.sessionKey;
    }
    
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    /**
     * 
     */
    public Integer getModuleExecutionId() {
        return this.moduleExecutionId;
    }
    
    public void setModuleExecutionId(Integer moduleExecutionId) {
        this.moduleExecutionId = moduleExecutionId;
    }

    /**
     * 
     */
    public String getFeatureView() {
        return this.featureView;
    }
    
    public void setFeatureView(String featureView) {
        this.featureView = featureView;
    }

    /**
     * 
     */
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * 
     */
    public Date getLastAccess() {
        return this.lastAccess;
    }
    
    public void setLastAccess(Date lastAccess) {
        this.lastAccess = lastAccess;
    }

    /**
     * 
     */
    public Date getStarted() {
        return this.started;
    }
    
    public void setStarted(Date started) {
        this.started = started;
    }

    /**
     * 
     */
    public String getImageView() {
        return this.imageView;
    }
    
    public void setImageView(String imageView) {
        this.imageView = imageView;
    }

    /**
     * 
     */
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * 
     */
    public Dataset getDataset() {
        return this.dataset;
    }
    
    public void setDataset(Dataset dataset) {
        this.dataset = dataset;
    }

    /**
     * 
     */
    public Experimenter getExperimenter() {
        return this.experimenter;
    }
    
    public void setExperimenter(Experimenter experimenter) {
        this.experimenter = experimenter;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}

  public boolean acceptFilter(Filter filter){


	  // Visiting: SessionId ------------------------------------------
	  Integer _SessionId = null;
	  try {
	     _SessionId = getSessionId();
	  } catch (Exception e) {
		 setSessionId(null);
	  }
// TODO catch class cast?
	  setSessionId((Integer) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):SessionId",_SessionId)); 

	  // Visiting: SessionKey ------------------------------------------
	  String _SessionKey = null;
	  try {
	     _SessionKey = getSessionKey();
	  } catch (Exception e) {
		 setSessionKey(null);
	  }
// TODO catch class cast?
	  setSessionKey((String) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):SessionKey",_SessionKey)); 

	  // Visiting: ModuleExecutionId ------------------------------------------
	  Integer _ModuleExecutionId = null;
	  try {
	     _ModuleExecutionId = getModuleExecutionId();
	  } catch (Exception e) {
		 setModuleExecutionId(null);
	  }
// TODO catch class cast?
	  setModuleExecutionId((Integer) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):ModuleExecutionId",_ModuleExecutionId)); 

	  // Visiting: FeatureView ------------------------------------------
	  String _FeatureView = null;
	  try {
	     _FeatureView = getFeatureView();
	  } catch (Exception e) {
		 setFeatureView(null);
	  }
// TODO catch class cast?
	  setFeatureView((String) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):FeatureView",_FeatureView)); 

	  // Visiting: Host ------------------------------------------
	  String _Host = null;
	  try {
	     _Host = getHost();
	  } catch (Exception e) {
		 setHost(null);
	  }
// TODO catch class cast?
	  setHost((String) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):Host",_Host)); 

	  // Visiting: LastAccess ------------------------------------------
	  Date _LastAccess = null;
	  try {
	     _LastAccess = getLastAccess();
	  } catch (Exception e) {
		 setLastAccess(null);
	  }
// TODO catch class cast?
	  setLastAccess((Date) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):LastAccess",_LastAccess)); 

	  // Visiting: Started ------------------------------------------
	  Date _Started = null;
	  try {
	     _Started = getStarted();
	  } catch (Exception e) {
		 setStarted(null);
	  }
// TODO catch class cast?
	  setStarted((Date) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):Started",_Started)); 

	  // Visiting: ImageView ------------------------------------------
	  String _ImageView = null;
	  try {
	     _ImageView = getImageView();
	  } catch (Exception e) {
		 setImageView(null);
	  }
// TODO catch class cast?
	  setImageView((String) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):ImageView",_ImageView)); 

	  // Visiting: Project ------------------------------------------
	  Project _Project = null;
	  try {
	     _Project = getProject();
	  } catch (Exception e) {
		 setProject(null);
	  }
// TODO catch class cast?
	  setProject((Project) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):Project",_Project)); 

	  // Visiting: Dataset ------------------------------------------
	  Dataset _Dataset = null;
	  try {
	     _Dataset = getDataset();
	  } catch (Exception e) {
		 setDataset(null);
	  }
// TODO catch class cast?
	  setDataset((Dataset) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):Dataset",_Dataset)); 

	  // Visiting: Experimenter ------------------------------------------
	  Experimenter _Experimenter = null;
	  try {
	     _Experimenter = getExperimenter();
	  } catch (Exception e) {
		 setExperimenter(null);
	  }
// TODO catch class cast?
	  setExperimenter((Experimenter) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.OmeSession):Experimenter",_Experimenter)); 
   	 return true;
  }
  
  public String toString(){
	return "OmeSession"+(sessionId==null ? ":Hash"+this.hashCode() : ":"+sessionId);
  }
  


}
