package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;


import java.util.*;




/**
 * SemanticElement generated by hbm2java
 */
public class
SemanticElement 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel {

    // Fields    

     private Integer semanticElementId;
     private String name;
     private String description;
     private SemanticType semanticType;


    // Constructors

    /** default constructor */
    public SemanticElement() {
    }
    
    /** constructor with id */
    public SemanticElement(Integer semanticElementId) {
        this.semanticElementId = semanticElementId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getSemanticElementId() {
        return this.semanticElementId;
    }
    
    public void setSemanticElementId(Integer semanticElementId) {
        this.semanticElementId = semanticElementId;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public SemanticType getSemanticType() {
        return this.semanticType;
    }
    
    public void setSemanticType(SemanticType semanticType) {
        this.semanticType = semanticType;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
