package org.openmicroscopy.omero.model;

import org.openmicroscopy.omero.BaseModelUtils;
import ome.util.Filterable;
import ome.util.Filter;


import java.util.*;




/**
 * SemanticType generated by hbm2java
 */
public class
SemanticType 
implements java.io.Serializable ,
org.openmicroscopy.omero.OMEModel,
ome.util.Filterable {

    // Fields    

     private Integer semanticTypeId;
     private String granularity;
     private String name;
     private String description;
     private Set semanticTypeOutputs;
     private Set formalOutputs;
     private Set formalInputs;
     private Set semanticElements;


    // Constructors

    /** default constructor */
    public SemanticType() {
    }
    
    /** constructor with id */
    public SemanticType(Integer semanticTypeId) {
        this.semanticTypeId = semanticTypeId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getSemanticTypeId() {
        return this.semanticTypeId;
    }
    
    public void setSemanticTypeId(Integer semanticTypeId) {
        this.semanticTypeId = semanticTypeId;
    }

    /**
     * 
     */
    public String getGranularity() {
        return this.granularity;
    }
    
    public void setGranularity(String granularity) {
        this.granularity = granularity;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public Set getSemanticTypeOutputs() {
        return this.semanticTypeOutputs;
    }
    
    public void setSemanticTypeOutputs(Set semanticTypeOutputs) {
        this.semanticTypeOutputs = semanticTypeOutputs;
    }

    /**
     * 
     */
    public Set getFormalOutputs() {
        return this.formalOutputs;
    }
    
    public void setFormalOutputs(Set formalOutputs) {
        this.formalOutputs = formalOutputs;
    }

    /**
     * 
     */
    public Set getFormalInputs() {
        return this.formalInputs;
    }
    
    public void setFormalInputs(Set formalInputs) {
        this.formalInputs = formalInputs;
    }

    /**
     * 
     */
    public Set getSemanticElements() {
        return this.semanticElements;
    }
    
    public void setSemanticElements(Set semanticElements) {
        this.semanticElements = semanticElements;
    }





	/** utility methods. Container may re-assign this. */	
	protected static org.openmicroscopy.omero.BaseModelUtils _utils = 
		new org.openmicroscopy.omero.BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}

  public boolean acceptFilter(Filter filter){


	  // Visiting: SemanticTypeId ------------------------------------------
	  Integer _SemanticTypeId = null;
	  try {
	     _SemanticTypeId = getSemanticTypeId();
	  } catch (Exception e) {
		 setSemanticTypeId(null);
	  }
// TODO catch class cast?
	  setSemanticTypeId((Integer) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):SemanticTypeId",_SemanticTypeId)); 

	  // Visiting: Granularity ------------------------------------------
	  String _Granularity = null;
	  try {
	     _Granularity = getGranularity();
	  } catch (Exception e) {
		 setGranularity(null);
	  }
// TODO catch class cast?
	  setGranularity((String) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):Granularity",_Granularity)); 

	  // Visiting: Name ------------------------------------------
	  String _Name = null;
	  try {
	     _Name = getName();
	  } catch (Exception e) {
		 setName(null);
	  }
// TODO catch class cast?
	  setName((String) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):Name",_Name)); 

	  // Visiting: Description ------------------------------------------
	  String _Description = null;
	  try {
	     _Description = getDescription();
	  } catch (Exception e) {
		 setDescription(null);
	  }
// TODO catch class cast?
	  setDescription((String) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):Description",_Description)); 

	  // Visiting: SemanticTypeOutputs ------------------------------------------
	  Set _SemanticTypeOutputs = null;
	  try {
	     _SemanticTypeOutputs = getSemanticTypeOutputs();
	  } catch (Exception e) {
		 setSemanticTypeOutputs(null);
	  }
// TODO catch class cast?
	  setSemanticTypeOutputs((Set) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):SemanticTypeOutputs",_SemanticTypeOutputs)); 

	  // Visiting: FormalOutputs ------------------------------------------
	  Set _FormalOutputs = null;
	  try {
	     _FormalOutputs = getFormalOutputs();
	  } catch (Exception e) {
		 setFormalOutputs(null);
	  }
// TODO catch class cast?
	  setFormalOutputs((Set) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):FormalOutputs",_FormalOutputs)); 

	  // Visiting: FormalInputs ------------------------------------------
	  Set _FormalInputs = null;
	  try {
	     _FormalInputs = getFormalInputs();
	  } catch (Exception e) {
		 setFormalInputs(null);
	  }
// TODO catch class cast?
	  setFormalInputs((Set) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):FormalInputs",_FormalInputs)); 

	  // Visiting: SemanticElements ------------------------------------------
	  Set _SemanticElements = null;
	  try {
	     _SemanticElements = getSemanticElements();
	  } catch (Exception e) {
		 setSemanticElements(null);
	  }
// TODO catch class cast?
	  setSemanticElements((Set) filter.filter("org.hibernate.mapping.RootClass(org.openmicroscopy.omero.model.SemanticType):SemanticElements",_SemanticElements)); 
   	 return true;
  }
  
  public String toString(){
	return "SemanticType"+(semanticTypeId==null ? ":Hash"+this.hashCode() : ":"+semanticTypeId);
  }
  


}
