#!/bin/bash
# /etc/rc.d/init.d/blitz
# Startup script for OMERO.blitz
#
# chkconfig: 345 80 20
# description: blitz (Image database) is the server part of the OMERO software.
#       The blitz server can be used to connect to the OMERO database
#       from all the languages supported by the Ice framework (Zeroc.com)
#
# config: /opt/omero/etc
# Source function library.

#Centos
test -e /etc/init.d/functions && {
    . /etc/init.d/functions
    my_success(){
	success "$@"
	true
    }
    my_failure(){
	failure "$@"
	false
    }
}

#Mac
test -e /etc/rc.common && {
    # . /etc/rc.common # RESETS PATH
    my_success(){
	echo "$@"
	true
    }
    my_failure(){
	echo "$@"
	false
    }
}

#Ubuntu
test -e /lib/lsb/init-functions && {
    . /lib/lsb/init-functions
    my_success(){
	log_success_msg "$@"
	true
    }
    my_failure(){
	log_failure_msg "$@"
	false
    }
}

#TESTINGONLY
#set -x
BLITZDIR=.
BLITZTAC=./blitz.tac
PID_FILE=./blitz.pid
LOG_FILE=./blitz.log
#LOGGER="--syslog"

BLITZDIR=${BLITZDIR:-"/opt/omero"}
BLITZTAC=${BLITZTAC:-"$BLITZDIR/blitz.tac"}
PID_FILE=${PID_FILE:-"/var/run/blitz.pid"}
LOG_FILE=${LOG_FILE:-"/var/log/blitz.log"}

LOGGER=${LOGGER:-"--logfile $LOG_FILE"}

twistd_y() {
    twistd -y $BLITZTAC $LOGGER \
	--pidfile $PID_FILE \
	--rundir $BLITZDIR \
	--prefix blitz
}

trap "echo Continuing..." SIGINT
while [ $# -gt 0 ]; do
   command=$1
   shift
  
   case "$command" in
     start)
       echo -n "Starting blitz: "
       twistd_y 
       if [ $? -eq 0 ]; then
      	   my_success "started"
       else 
	   my_failure "can't start via $BLITZTAC"
       fi
       ;;
     stop)
       echo -n "Stopping blitz: "
       if test -f $PID_FILE; then
	   kill `cat $PID_FILE`
	   my_success "stopped"
       else
	   my_failure "can't find $PID_FILE"
       fi
       echo
       ;;
     status)
	   echo "OMERO.blitz:" unknown
	;;
     restart)
      	   $0 stop
	   $0 start
       ;;
     tail)
	   tail -f $LOG_FILE
       ;;
     grep)
	   ps aux | grep -E "(blitz|glacier)"
       ;;
     console)
	   $0 start tail stop
       ;;
     *)
       echo "Usage: $0 {start|stop|status|restart}"
       false
   esac
done
