package ome.model.core;

import ome.util.BaseModelUtils;


import java.util.*;




/**
 * Roi2DZRange generated by hbm2java
 */
public class
Roi2DZRange extends ome.model.core.Roi2D
implements java.io.Serializable ,
ome.api.OMEModel
, ome.NewModel 
{

    // Fields    

     private Integer minZ;
     private Integer maxZ;


    // Constructors

    /** default constructor */
    public Roi2DZRange() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getMinZ() {
        return this.minZ;
    }
    
    public void setMinZ(Integer minZ) {
        this.minZ = minZ;
    }

    /**
     * 
     */
    public Integer getMaxZ() {
        return this.maxZ;
    }
    
    public void setMaxZ(Integer maxZ) {
        this.maxZ = maxZ;
    }





	/** utility methods. Container may re-assign this. */	
	protected static BaseModelUtils _utils = 
		new BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
