package ome.model.core;

import ome.util.BaseModelUtils;


import java.util.*;




/**
 * Roi4DChannelRange generated by hbm2java
 */
public class
Roi4DChannelRange extends ome.model.core.Roi4D
implements java.io.Serializable ,
ome.api.OMEModel {

    // Fields    

     private Integer minC;
     private Integer maxC;


    // Constructors

    /** default constructor */
    public Roi4DChannelRange() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getMinC() {
        return this.minC;
    }
    
    public void setMinC(Integer minC) {
        this.minC = minC;
    }

    /**
     * 
     */
    public Integer getMaxC() {
        return this.maxC;
    }
    
    public void setMaxC(Integer maxC) {
        this.maxC = maxC;
    }





	/** utility methods. Container may re-assign this. */	
	protected static BaseModelUtils _utils = 
		new BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
