package ome.model.meta;

import ome.util.BaseModelUtils;


import java.util.*;




/**
 * Event generated by hbm2java
 */
public class
Event 
implements java.io.Serializable ,
ome.api.OMEModel
{

    // Fields    

     private Integer id;
     private String name;


    // Constructors

    /** default constructor */
    public Event() {
    }
    
    /** constructor with id */
    public Event(Integer id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }





	/** utility methods. Container may re-assign this. */	
	protected static BaseModelUtils _utils = 
		new BaseModelUtils();
	public BaseModelUtils getUtils(){
		return _utils;
	}
	public void setUtils(BaseModelUtils utils){
		_utils = utils;
	}



}
