#!/usr/bin/env python
# encoding: utf-8

"""
Retrieves the JARs from the latest Hudson based build of the LOCI software
repository; predominently Bio-Formats.
"""

# Copyright (C) 2009 University of Dundee

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


import urllib

# Handle Python 2.5 built-in ElementTree
try:
        from xml.etree.ElementTree import XML, ElementTree, tostring
except ImportError:
        from elementtree.ElementTree import XML, ElementTree, tostring

# JARs to ignore from download
ignore = ["loci_tools.jar"]

url = urllib.urlopen("http://hudson.openmicroscopy.org.uk/job/LOCI/lastBuild/api/xml")
hudson_xml = url.read()
url.close()

root = XML(hudson_xml)

revision = root.find("./changeSet/revision/revision").text
artifacts = root.findall("./artifact")

print "Updating Bio-Formats JARs from revision: %s" % revision
base_url = "http://hudson.openmicroscopy.org.uk/job/LOCI/lastBuild/artifact/"
for artifact in artifacts:
    filename = artifact.find("fileName").text
    if filename in ignore:
        continue
    filename = "%s-r%s.jar" % (filename[:-4], revision)
    jar_url = base_url + artifact.find("relativePath").text
    print "Downloading %s from URL %s" % (filename, jar_url)
    urllib.urlretrieve(jar_url, filename)
