Test Fixture Settings
+++++++++++++++++++++

+---------+--------------+
| Setting | Value        |
+=========+==============+
| Library | SwingLibrary |
+---------+--------------+

Test Fixture Keywords
+++++++++++++++++++++

+------------------+----------------------------+---------------------------------+------------------------------------------+
| Keyword          | Action                     | Argument                        | Argument                                 |
+==================+============================+=================================+==========================================+
| Thumbnail Should | [Documentation]            | expects that the thumbnail      |                                          |
| Be Blank         |                            | image is monochromatic          |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | [Arguments]                | ${image_name}                   |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | ${is_monochromatic}=       | Is Thumbnail Monochromatic      | ${image_name}                            |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | Should Be True             | ${is_monochromatic}             |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| Thumbnail Should | [Documentation]            | expects that the thumbnail      |                                          |
| Not Be Blank     |                            | image is polychromatic          |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | [Arguments]                | ${image_name}                   |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | ${is_monochromatic}=       | Is Thumbnail Monochromatic      | ${image_name}                            |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | Should Not Be True         | ${is_monochromatic}             |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| Click Thumbnail  | [Documentation]            | click on the thumbnail          |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | [Arguments]                | ${image_name}                   |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | ${thumbnail}=              | Get Name Of Thumbnail For Image | ${image_name}                            |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | Click On Component         | ${thumbnail}                    |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| Thumbnail Should | [Documentation]            | expects that the thumbnail is   |                                          |
| Not Be Selected  |                            | not selected                    |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | [Arguments]                | ${image_name}                   |                                          |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | ${unselected_color}=       | Get AWT Color                   | util.ui.border.FrameBorder.DEFAULT_COLOR |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | ${thumbnail_color}=        | Get Thumbnail Border Color      | ${image_name}                            |
+------------------+----------------------------+---------------------------------+------------------------------------------+
| ..               | Should Be Equal            | ${unselected_color}             | ${thumbnail_color}                       |
+------------------+----------------------------+---------------------------------+------------------------------------------+
